/*!
 * Distil — hearing clinic patient management & intake system
 *
 * Copyright (c) 2026 Kurt Mooney. All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL. This source code is the exclusive property of
 * the copyright holder. Unauthorized copying, distribution, modification, or
 * use of this file, in whole or in part, via any medium, is strictly
 * prohibited without the prior written permission of the copyright holder.
 * See the LICENSE file at the repository root for full terms.
 */

// ── Legacy device reference — offline fallback ───────────────────────────────
// Mirror of the public.legacy_device table (see supabase/migrations/
// 20260630010000_seed_legacy_devices.sql). Curated trade-in / competitor / older
// devices so the old-vs-new comparator (src/deviceComparison.js) can score a
// patient's CURRENT aid when it was never fit by us. The live screen reads the
// DB via loadLegacyDevices(); this is the fallback if that query fails.
// Keep in sync with the seed migration — it is a fallback only.
//
// original_tier_rank uses the sparse COVERAGE_BY_RANK scale (5 Premium / 3
// Advanced / 1 Standard). Specs carry source_url + confidence for defensibility.
export const LEGACY_DEVICES_DEFAULT = [
  {"id":"costco-ks7","manufacturer":"Rexton","brand":"Costco Kirkland Signature","model":"KS7.0","aliases":["KS7","Kirkland Signature 7","Rexton-based","Signia 7px-class"],"releaseYear":2016,"platform":"Rexton/Sivantos (Signia primax-class)","originalTierLabel":"Advanced","originalTierRank":3,"formFactors":["ric"],"channels":20,"directionalMic":"adaptive","rechargeable":false,"bluetoothStreaming":false,"telecoil":true,"ipRating":null,"notableFeatures":["48 processing channels / 20 gain handles","streams via intermediary streamer (no direct-to-phone)","312 battery","4 receiver power levels"],"sourceUrl":"https://forum.hearingtracker.com/t/costco-kirkland-signature-7-0-product-information/25240","confidence":"medium"},
  {"id":"costco-ks8","imageKey":"signia-pure-nx","manufacturer":"Rexton","brand":"Costco Kirkland Signature","model":"KS8.0","aliases":["KS8","Kirkland Signature 8","Signia Pure 312 7Nx-clone","Rexton-based"],"releaseYear":2018,"platform":"Rexton/Sivantos (Signia Nx-class)","originalTierLabel":"Advanced","originalTierRank":3,"formFactors":["ric"],"channels":20,"directionalMic":"adaptive","rechargeable":false,"bluetoothStreaming":true,"telecoil":true,"ipRating":null,"notableFeatures":["Made for iPhone (MFi) direct streaming","48 processing channels / 20 gain handles","spec-identical to Signia Pure 312 7Nx","312 or 13 (T) battery"],"sourceUrl":"https://forum.hearingtracker.com/t/costco-kirkland-signature-8-0-product-information/34162","confidence":"high"},
  {"id":"costco-ks9","imageKey":"phonak-audeo-marvel","manufacturer":"Phonak","brand":"Costco Kirkland Signature","model":"KS9.0","aliases":["KS9","Kirkland Signature 9","Marvel-based","Phonak M90-class"],"releaseYear":2019,"platform":"Phonak Marvel-class (Sonova)","originalTierLabel":"Advanced","originalTierRank":3,"formFactors":["ric"],"channels":20,"directionalMic":"beamforming","rechargeable":false,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["direct iOS + Android + any-phone Bluetooth streaming","AutoSense OS","20 fine-tuning bands","Marvel M90-equivalent silicon","312 battery (non-rechargeable variant)"],"sourceUrl":"https://hearingreview.com/uncategorized/sonova-to-supply-costco-kirkland-signature-ks9-hearing-aids","confidence":"high"},
  {"id":"costco-ks10","imageKey":"phonak-audeo-paradise","manufacturer":"Phonak","brand":"Costco Kirkland Signature","model":"KS10.0","aliases":["KS10","KS10.0T","Kirkland Signature 10","Paradise-based","Phonak P90-class"],"releaseYear":2021,"platform":"Phonak Paradise-class (Sonova)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric"],"channels":20,"directionalMic":"beamforming","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["Paradise P90-equivalent silicon","motion sensors + Tap Control","Echo Manager, Speech Enhancer","Made for Any Phone Bluetooth (2 active connections)","Li-ion rechargeable","KS10.0T adds telecoil"],"sourceUrl":"https://www.hearingtracker.com/hearing-aids/kirkland-signature-costco-10","confidence":"high"},
  {"id":"phonak-audeo-marvel-m90","imageKey":"phonak-audeo-marvel","manufacturer":"Phonak","brand":"Phonak","model":"Audeo Marvel M90","aliases":["M90","Audeo M90-R","Marvel 90"],"releaseYear":2018,"platform":"Phonak Marvel (AutoSense OS 3.0)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte"],"channels":20,"directionalMic":"beamforming","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["direct iOS + Android + classic Bluetooth streaming","AutoSense OS 3.0","hands-free calls","StereoZoom","echo reduction (M90 only)","Li-ion rechargeable (M-R)"],"sourceUrl":"https://www.phonakpro.com/content/dam/phonakpro/gc_us/en/marketing/documents/marvel/028-1905-03_Leaflet_BtB_Phonak_Audeo_Marvel.pdf","confidence":"high"},
  {"id":"phonak-audeo-paradise-p90","imageKey":"phonak-audeo-paradise","manufacturer":"Phonak","brand":"Phonak","model":"Audeo Paradise P90","aliases":["P90","Audeo P90-R","Paradise 90"],"releaseYear":2020,"platform":"Phonak Paradise (AutoSense OS 4.0)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte"],"channels":20,"directionalMic":"beamforming","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["motion sensors + Tap Control","StereoZoom, Speech Enhancer, Dynamic Noise Cancellation","Made for Any Phone (2 active Bluetooth connections)","AutoSense OS 4.0","Li-ion rechargeable"],"sourceUrl":"https://www.phonak.com/en-us/hearing-devices/hearing-aids/audeo-paradise","confidence":"high"},
  {"id":"phonak-audeo-lumity-l90","imageKey":"phonak-audeo-lumity","manufacturer":"Phonak","brand":"Phonak","model":"Audeo Lumity L90","aliases":["L90","Audeo L90-R","Lumity 90"],"releaseYear":2022,"platform":"Phonak Lumity (AutoSense OS 5.0 / SmartSpeech)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte"],"channels":20,"directionalMic":"beamforming","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["SmartSpeech Technology, StereoZoom 2.0, SpeechSensor","up to 30h battery per charge","Bluetooth Classic + iOS/Android direct streaming","9 automatic programs","Li-ion rechargeable"],"sourceUrl":"https://www.phonak.com/en-us/hearing-devices/hearing-aids/audeo-lumity","confidence":"high"},
  {"id":"signia-pure-7nx","imageKey":"signia-pure-nx","manufacturer":"Signia","brand":"Signia","model":"Pure 312 7Nx","aliases":["7Nx","Pure Nx","Signia Nx generation"],"releaseYear":2018,"platform":"Signia Nx (Own Voice Processing)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte"],"channels":48,"directionalMic":"beamforming","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["Own Voice Processing (OVP)","48 channels","narrow/ultra-HD directionality (beamforming)","Made for iPhone direct streaming","Charge&Go Li-ion rechargeable option"],"sourceUrl":"https://www.signia-pro.com/en-us/product-portfolio/signia-nx/","confidence":"high"},
  {"id":"signia-pure-7ax","imageKey":"signia-pure-ax","manufacturer":"Signia","brand":"Signia","model":"Pure Charge&Go 7AX","aliases":["7AX","Pure AX","Augmented Xperience"],"releaseYear":2021,"platform":"Signia Augmented Xperience (AX) - dual processor","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric"],"channels":48,"directionalMic":"beamforming","rechargeable":true,"bluetoothStreaming":true,"telecoil":false,"ipRating":"IP68","notableFeatures":["Augmented Focus dual-processor (separate speech + environment)","48 channels","iOS + Android direct streaming","Li-ion Charge&Go rechargeable","T AX variant adds telecoil"],"sourceUrl":"https://www.hearingtracker.com/hearing-aids/signia-pure-ax","confidence":"high"},
  {"id":"oticon-opn-1","imageKey":"oticon-opn","manufacturer":"Oticon","brand":"Oticon","model":"Opn 1","aliases":["Opn1","Opn 1 miniRITE","OpenSound"],"releaseYear":2016,"platform":"Oticon Velox (OpenSound Navigator)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte"],"channels":64,"directionalMic":"adaptive","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["OpenSound Navigator (open, non-blocking directionality)","64 processing channels","Made for iPhone (2.4 GHz) streaming","internet/IoT connectivity via If This Then That","retrofit rechargeable (ZPower/Li-ion) option","miniRITE-T telecoil variant"],"sourceUrl":"https://www.oticon.com/-/media/oticon-us/main/download-center/opn/product-information/179076us_td_opn1-2-3_minirite-minirite-t_85.pdf","confidence":"high"},
  {"id":"oticon-more-1","imageKey":"oticon-more","manufacturer":"Oticon","brand":"Oticon","model":"More 1","aliases":["More1","More 1 miniRITE R","Oticon More"],"releaseYear":2021,"platform":"Oticon Polaris (Deep Neural Network / MoreSound Intelligence)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte"],"channels":64,"directionalMic":"adaptive","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["on-board Deep Neural Network (MoreSound Intelligence)","64 channels","MFi + hands-free calling (later ASHA Android)","Li-ion rechargeable (miniRITE R)","miniRITE T telecoil/disposable variant"],"sourceUrl":"https://www.earpros.com/hearing-aid-brands/oticon-hearing-aids/more","confidence":"high"},
  {"id":"resound-one-9","imageKey":"resound-one","manufacturer":"ReSound","brand":"ReSound","model":"ONE 9","aliases":["ONE 9","One 9","GN ReSound ONE 9","M&RIE"],"releaseYear":2020,"platform":"ReSound (M&RIE third microphone)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte"],"channels":17,"directionalMic":"adaptive","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["M&RIE (Microphone & Receiver-in-Ear) third in-canal mic","17 channels / bands","Made for iPhone + ASHA Android direct streaming","up to 30h Li-ion rechargeable","All Access Directionality"],"sourceUrl":"https://www.hearingtracker.com/hearing-aids/resound-one","confidence":"high"},
  {"id":"resound-nexia-9","imageKey":"resound-nexia-ric","manufacturer":"ReSound","brand":"ReSound","model":"Nexia 9","aliases":["Nexia 9","GN ReSound Nexia 9","Auracast"],"releaseYear":2024,"platform":"ReSound (Bluetooth LE Audio / Auracast)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte","ite","itc","cic","iic"],"channels":17,"directionalMic":"adaptive","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["Bluetooth LE Audio + Auracast broadcast reception","17 channels / 20 adjustment bands","iOS + Android direct streaming","up to 30h Li-ion (24h w/ streaming)","smallest ReSound rechargeable RIE"],"sourceUrl":"https://www.hearingtracker.com/hearing-aids/resound-nexia","confidence":"high"},
  {"id":"starkey-livio-ai-2400","imageKey":"starkey-livio","manufacturer":"Starkey","brand":"Starkey","model":"Livio AI 2400","aliases":["Livio AI","Livio AI 2400","Healthable"],"releaseYear":2018,"platform":"Starkey Livio (Thrive / Healthable AI)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte","ite","itc","cic"],"channels":24,"directionalMic":"adaptive","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["first 'Healthable' - heart rate, activity, fall detection, Thrive Assistant","Made for iPhone direct streaming (Android via streamer)","language translation + transcription","Li-ion rechargeable option"],"sourceUrl":"https://www.hearingtracker.com/hearing-aids/starkey-livio","confidence":"medium"},
  {"id":"starkey-genesis-ai-24","imageKey":"starkey-genesis-ric","manufacturer":"Starkey","brand":"Starkey","model":"Genesis AI 24","aliases":["Genesis AI 24","Genesis 24","Neuro Processor"],"releaseYear":2023,"platform":"Starkey Genesis AI (Neuro Processor)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte","ite","itc","cic","iic"],"channels":24,"directionalMic":"adaptive","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["Neuro Processor with on-board deep neural network","Neuro Sound Technology (up to 80M automatic adjustments/hr)","iOS + Android direct streaming, hands-free iOS calls","health/fitness tracking + fall detection","Li-ion rechargeable (new sealed design)"],"sourceUrl":"https://www.hearingtracker.com/hearing-aids/starkey-genesis-ai","confidence":"high"},
  {"id":"widex-moment-440","imageKey":"widex-moment-ric","manufacturer":"Widex","brand":"Widex","model":"Moment 440","aliases":["Moment 440","mRIC 440","PureSound / ZeroDelay"],"releaseYear":2020,"platform":"Widex Moment (ZeroDelay / PureSound)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte","ite","itc","cic"],"channels":15,"directionalMic":"adaptive","rechargeable":true,"bluetoothStreaming":true,"telecoil":true,"ipRating":"IP68","notableFeatures":["ZeroDelay Accelerator / PureSound (ultra-low latency)","15 processing channels / 5 programs","Made for iPhone + ASHA Android streaming","Li-ion rechargeable option","SoundSense Learn AI personalization"],"sourceUrl":"https://www.hearingtracker.com/hearing-aids/widex-moment","confidence":"high"},
  {"id":"widex-moment-sheer-440","imageKey":"widex-moment-sheer","manufacturer":"Widex","brand":"Widex","model":"Moment Sheer 440","aliases":["Moment Sheer 440","Sheer sRIC R D","sRIC"],"releaseYear":2022,"platform":"Widex Moment Sheer (PureSound / TruAcoustics)","originalTierLabel":"Premium","originalTierRank":5,"formFactors":["ric","bte","ite","itc","cic"],"channels":15,"directionalMic":"adaptive","rechargeable":true,"bluetoothStreaming":true,"telecoil":false,"ipRating":"IP68","notableFeatures":["PureSound ZeroDelay + TruAcoustics personalization","redesigned smaller sRIC R D shell","up to 29h Li-ion rechargeable","iOS + Android direct streaming, hands-free calls","15 processing channels"],"sourceUrl":"https://www.hearingaid.org.uk/hearing-aids/widex/moment-sheer","confidence":"high"},
];
