/*!
 * Distil — hearing clinic patient management & intake system
 *
 * Copyright (c) 2026 Kurt Mooney. All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL. This source code is the exclusive property of
 * the copyright holder. Unauthorized copying, distribution, modification, or
 * use of this file, in whole or in part, via any medium, is strictly
 * prohibited without the prior written permission of the copyright holder.
 * See the LICENSE file at the repository root for full terms.
 */

// ── NationsBenefits (Nations Hearing) covered-device catalog ─────────────────
// The authoritative Nations catalog: every SKU Nations covers, with its Nations
// tier. Source: "NationsBenefits Hearing Aids Pricing Catalog" spreadsheet
// (Drive: Distil CRM/Insurance, exported 2026-07-06; 637 SKUs). Per-aid copay
// and fitting fee are FLAT per tier — every device in a tier costs the patient
// the same — so they live once in NATIONS_TIER_PRICING rather than on each row.
// Model strings are verbatim from Nations (their portal's order identifiers);
// brand is derived from Nations' prefix (GNR → ReSound).
//
// This dataset is REFERENCE data for the Admin → Nations Catalog view and the
// drift test in lib/nationsCatalog.test.js. Live pricing does NOT read it:
// device→tier resolution stays in nationsCoverageTier() (lib/pricing.js) keyed
// on product_catalog families, and tier copays come from the insurance_plans
// row (Aetna · Nations Hearing). Beltone/Bernafon/Unitron rows are shown for
// completeness but MHC doesn't dispense them (Beltone needs proprietary
// software auth we lack — see CLAUDE.md).

// Tier order (Standard → Specialty) lives in lib/pricing.js as
// NATIONS_TIER_ORDER — import from there; not duplicated here.

// Per-aid dollars. Copay = "Unit Price" (member responsibility per aid);
// fitting fee = "Unit Fitting Fee". Pair values are exactly 2x — not stored.
export const NATIONS_TIER_PRICING = {
  Standard:         { copayPerAid: 600, fittingFeePerAid: 200 },
  Select:           { copayPerAid: 800, fittingFeePerAid: 215 },
  'Superior Plus':  { copayPerAid: 1150, fittingFeePerAid: 300 },
  Advanced:         { copayPerAid: 1450, fittingFeePerAid: 400 },
  'Advanced Plus':  { copayPerAid: 1625, fittingFeePerAid: 550 },
  Specialty:        { copayPerAid: 2000, fittingFeePerAid: 700 },
};

// [brand, model, tier] tuples — tuple array keeps 637 rows compact.
export const NATIONS_CATALOG = [
  ['ReSound', 'GNR RSKEY3_KE377-DW', 'Standard'],
  ['ReSound', 'GNR RSKEY3_KE388-DWH', 'Standard'],
  ['ReSound', 'GNR RSKEY3_KE398-DW', 'Standard'],
  ['Beltone', 'BELTONE BTXC2_XC261-DRW', 'Standard'],
  ['Beltone', 'BELTONE BTXC2_XC262-DRW', 'Standard'],
  ['Beltone', 'BELTONE BTXC2_XC267-DW', 'Standard'],
  ['Beltone', 'BELTONE BTXC2_XC277-DW', 'Standard'],
  ['Beltone', 'BELTONE BTXC2_XC288-DWH', 'Standard'],
  ['Beltone', 'BELTONE BTXC2_XC298-DW', 'Standard'],
  ['ReSound', 'GNR SAVI2_SA261-DRW', 'Standard'],
  ['ReSound', 'GNR SAVI2_SA262-DRW', 'Standard'],
  ['Beltone', 'BELTONE XH2_XH261-DRW', 'Standard'],
  ['Beltone', 'BELTONE XH2_XH262-DRW', 'Standard'],
  ['ReSound', 'GNR ENZOCORE2_EC298-DW', 'Standard'],
  ['ReSound', 'GNR RSSAVI2_SA2CIC', 'Standard'],
  ['ReSound', 'GNR RSSAVI2_SA2HSB', 'Standard'],
  ['ReSound', 'GNR RSSAVI2_SA2ITCB', 'Standard'],
  ['Beltone', 'BELTONE BTXH2_XH2ITCB', 'Standard'],
  ['Starkey', 'STARKEY 10_STARKEY.G SERIES AI.10.BTE.13.PWRPLS', 'Standard'],
  ['Starkey', 'STARKEY 10_STARKEY.G SERIES AI.10.BTE.13.STD', 'Standard'],
  ['Starkey', 'STARKEY 10_STARKEY.G SERIES AI.10.RIC.312.STD', 'Standard'],
  ['Widex', 'WIDEX WI Evoke BTE 220_EBB13D', 'Select'],
  ['Widex', 'WIDEX WI Evoke RIC 220_ERB312', 'Select'],
  ['Rexton', 'Rexton REXBicore RIC 312 30', 'Select'],
  ['Rexton', 'Rexton REXBicore BTE B HP 30', 'Select'],
  ['Rexton', 'Rexton REXBicore BTE B M 30', 'Select'],
  ['Rexton', 'Rexton REXBicore BTE B P 30', 'Select'],
  ['Rexton', 'Rexton REXBicore SR 30', 'Select'],
  ['Widex', 'WIDEX WI Evoke CIC 220_E2CIC', 'Select'],
  ['Widex', 'WIDEX WI Evoke CIC 220_E2CIC_MICRO', 'Select'],
  ['Widex', 'WIDEX WI Evoke Fashion 220_E2FAV', 'Select'],
  ['Widex', 'WIDEX WI Evoke Fashion 220_E2FM', 'Select'],
  ['Widex', 'WIDEX WI Evoke Canal 220_E2IMLC', 'Select'],
  ['Widex', 'WIDEX WI Evoke Canal 220_E2CIC', 'Select'],
  ['Widex', 'WIDEX WI Evoke Shell 220_E2IMS', 'Select'],
  ['Widex', 'WIDEX WI Evoke Canal 220_E2IPC', 'Select'],
  ['Widex', 'WIDEX WI Evoke Shell 220_E2IPS', 'Select'],
  ['Widex', 'WIDEX WI Evoke Shell 220_E2XPFS', 'Select'],
  ['Widex', 'WIDEX WI Evoke Shell 220_E2XPHS', 'Select'],
  ['Widex', 'WIDEX WI Evoke Canal 220_E2XPPC', 'Select'],
  ['Widex', 'WIDEX WI Evoke RIC 220_ERB10', 'Select'],
  ['Unitron', 'UNITRON 3_Insera B3-10 NW O', 'Select'],
  ['Unitron', 'UNITRON 3_Insera B3-312', 'Select'],
  ['Unitron', 'UNITRON 3_Insera B3-312 NW O', 'Select'],
  ['ReSound', 'GNR RSKEY4_KE477-DW', 'Select'],
  ['ReSound', 'GNR RSKEY4_KE488-DWH', 'Select'],
  ['ReSound', 'GNR RSKEY4_KE498-DW', 'Select'],
  ['Unitron', 'UNITRON 3_Moxi V3-312', 'Select'],
  ['Unitron', 'UNITRON 3_Moxi V3-R', 'Select'],
  ['Unitron', 'UNITRON 3_Moxi V3-RT', 'Select'],
  ['Phonak', 'PHONAK L30_Phonak Audeo L30-312', 'Select'],
  ['Phonak', 'PHONAK L30_Phonak Audeo L30-R', 'Select'],
  ['Phonak', 'PHONAK L30_Phonak Audeo L30-RT', 'Select'],
  ['Phonak', 'PHONAK L30_Phonak Naida L30-PR', 'Select'],
  ['Phonak', 'PHONAK L30_Phonak Naida L30-SP', 'Select'],
  ['Phonak', 'PHONAK L30_Phonak Naida L30-UP', 'Select'],
  ['Phonak', 'PHONAK P30_Phonak Virto P30-312', 'Select'],
  ['Phonak', 'PHONAK P30_Phonak Virto P30-312 NW O', 'Select'],
  ['Unitron', 'UNITRON 3_Stride V3-PR', 'Select'],
  ['Unitron', 'UNITRON 3_Stride V3-UP', 'Select'],
  ['Beltone', 'BELTONE BTXC3_XC361-DRW', 'Select'],
  ['Beltone', 'BELTONE BTXC3_XC361-DRWC', 'Select'],
  ['Beltone', 'BELTONE BTXC3_XC362-DRW', 'Select'],
  ['Beltone', 'BELTONE BTXC3_XC367-DW', 'Select'],
  ['Beltone', 'BELTONE BTXC3_XC377-DW', 'Select'],
  ['Beltone', 'BELTONE BTXC3_XC388-DWH', 'Select'],
  ['Beltone', 'BELTONE BTXC3_XC398-DW', 'Select'],
  ['Bernafon', 'BERNAFON BER_Alpha_3_mRITE_T', 'Select'],
  ['Rexton', 'Rexton REXBicore RIC R LI T 30', 'Select'],
  ['ReSound', 'GNR SAVI3_SA360-DRWC', 'Select'],
  ['ReSound', 'GNR SAVI3_SA361-DRW', 'Select'],
  ['ReSound', 'GNR SAVI3_SA362-DRW', 'Select'],
  ['Unitron', 'UNITRON 3_Stride V3-M', 'Select'],
  ['Unitron', 'UNITRON 3_Stride V3-SP', 'Select'],
  ['Beltone', 'BELTONE XH3_XH360-DRWC', 'Select'],
  ['Beltone', 'BELTONE XH3_XH361-DRW', 'Select'],
  ['Beltone', 'BELTONE XH3_XH362-DRW', 'Select'],
  ['Phonak', 'PHONAK L30_Phonak Naida L30-M', 'Select'],
  ['Rexton', 'Rexton REX Reach Custom 30', 'Select'],
  ['Rexton', 'Rexton REX REACH IX-CIC LI 30 SL', 'Select'],
  ['Rexton', 'Rexton REX REACH IX-CIC LI 30 SR', 'Select'],
  ['ReSound', 'GNR ENZOCORE3_EC398-DW', 'Select'],
  ['ReSound', 'GNR RSSAVI3_SA3CIC', 'Select'],
  ['ReSound', 'GNR RSSAVI3_SA3HSB', 'Select'],
  ['ReSound', 'GNR RSSAVI3_SA3ITCB', 'Select'],
  ['Beltone', 'BELTONE BTXH2_XH2CIC', 'Select'],
  ['Starkey', 'STARKEY 1000_STARKEY.EVOLV AI.1000.BTE.R.STD', 'Select'],
  ['Starkey', 'STARKEY 10_STARKEY.G SERIES AI.10.RIC.R.STD', 'Select'],
  ['Signia', 'SIGNIA SI2AX_PURE312', 'Superior Plus'],
  ['Signia', 'SIGNIA SI2AX_PURECHARGEANDGO', 'Superior Plus'],
  ['Signia', 'SIGNIA SI2AX_STYLETTO', 'Superior Plus'],
  ['Bernafon', 'BERNAFON BER_AlphaXT_AXT_5_mRITE_R', 'Superior Plus'],
  ['Bernafon', 'BERNAFON BER_AlphaXT_AXT_5_mRITE_T', 'Superior Plus'],
  ['Bernafon', 'BERNAFON BER_AlphaXT_AXT_7_mRITE_R', 'Superior Plus'],
  ['Bernafon', 'BERNAFON BER_AlphaXT_AXT_7_mRITE_T', 'Superior Plus'],
  ['Unitron', 'UNITRON 5_Insera B5-10 NW O', 'Superior Plus'],
  ['Unitron', 'UNITRON 5_Insera B5-312', 'Superior Plus'],
  ['Unitron', 'UNITRON 5_Insera B5-312 NW O', 'Superior Plus'],
  ['Signia', 'SIGNIA SI2AX_INSIO_CHARGE_AND_GO_2AX', 'Superior Plus'],
  ['ReSound', 'GNR RSKEY3_KE3HS', 'Superior Plus'],
  ['ReSound', 'GNR RSKEY3_KE3ITC', 'Superior Plus'],
  ['ReSound', 'GNR RSKEY3_KE3ITE', 'Superior Plus'],
  ['ReSound', 'GNR RSKEY4_KE4HS', 'Superior Plus'],
  ['ReSound', 'GNR RSKEY4_KE4ITC', 'Superior Plus'],
  ['ReSound', 'GNR RSKEY4_KE4ITE', 'Superior Plus'],
  ['Widex', 'WIDEX WI Moment BTE 13D 110_MBB3D1', 'Superior Plus'],
  ['Widex', 'WIDEX WI Custom CIC 110_MCIC1', 'Superior Plus'],
  ['Widex', 'WIDEX WI Custom CIC 110_MCICM1', 'Superior Plus'],
  ['Widex', 'WIDEX WI Moment IM 110 C_MIM1C', 'Superior Plus'],
  ['Widex', 'WIDEX WI Custom IM 110 FS_MIM1F', 'Superior Plus'],
  ['Widex', 'WIDEX WI Moment IM 110 HS_MIM1H', 'Superior Plus'],
  ['Widex', 'WIDEX WI Custom IP 110 C_MIP1C', 'Superior Plus'],
  ['Widex', 'WIDEX WI Moment IP 110 FS_MIP1F', 'Superior Plus'],
  ['Widex', 'WIDEX WI Custom IP 110 HS_MIP1H', 'Superior Plus'],
  ['Oticon', 'OTICON OTMORE3_BTE_R', 'Superior Plus'],
  ['Oticon', 'OTICON OTMORE3_BTE_T', 'Superior Plus'],
  ['Oticon', 'OTICON OTMORE3_MRITE_R', 'Superior Plus'],
  ['Oticon', 'OTICON OTMORE3_MRITE_T', 'Superior Plus'],
  ['Widex', 'WIDEX WI Moment RIC 110_MRB01', 'Superior Plus'],
  ['Widex', 'WIDEX WI Moment RIC 312 110_MRB2D1', 'Superior Plus'],
  ['Widex', 'WIDEX WI Custom XP 110 C_MXP1C', 'Superior Plus'],
  ['Widex', 'WIDEX WI Moment XP 110 FS_MXP1F', 'Superior Plus'],
  ['Widex', 'WIDEX WI Custom XP 110 HS_MXP1H', 'Superior Plus'],
  ['Oticon', 'OTICON OTOWN4_CIC_10', 'Superior Plus'],
  ['Oticon', 'OTICON OTOWN4_IIC_10', 'Superior Plus'],
  ['Oticon', 'OTICON OTOWN4_ITC_312', 'Superior Plus'],
  ['Oticon', 'OTICON OTOWN4_ITE_312', 'Superior Plus'],
  ['Oticon', 'OTICON OTOWN5_CIC_10', 'Superior Plus'],
  ['Oticon', 'OTICON OTOWN5_IIC_10', 'Superior Plus'],
  ['Oticon', 'OTICON OTOWN5_ITC_312', 'Superior Plus'],
  ['Oticon', 'OTICON OTOWN5_ITE_312', 'Superior Plus'],
  ['Phonak', 'PHONAK I30_Phonak Audeo I30-R', 'Superior Plus'],
  ['Signia', 'SIGNIA SIT2AX_PURECHARGEANDGO', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC3_XC3CIC', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC3_XC3HS', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC3_XC3ITC', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC3_XC3ITE', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC4_XC461-DRW', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC4_XC461-DRWC', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC4_XC462-DRW', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC4_XC467-DW', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC4_XC477-DW', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC4_XC488-DWH', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXC4_XC498-DW', 'Superior Plus'],
  ['Oticon', 'OTICON OTZIRCON2_BTE_R', 'Superior Plus'],
  ['Oticon', 'OTICON OTZIRCON2_BTE_T', 'Superior Plus'],
  ['Oticon', 'OTICON OTZIRCON2_MRITE_R', 'Superior Plus'],
  ['Oticon', 'OTICON OTZIRCON2_MRITE_T', 'Superior Plus'],
  ['Signia', 'SIGNIA SI_Active_IX', 'Superior Plus'],
  ['Signia', 'SIGNIA SI_INTUIS_M_4_2', 'Superior Plus'],
  ['Signia', 'SIGNIA SI_INTUIS_P_4_2', 'Superior Plus'],
  ['Signia', 'SIGNIA SI_INTUIS_SP_4_2', 'Superior Plus'],
  ['Signia', 'SIGNIA SI2IX_INSIO_2IX_CIC', 'Superior Plus'],
  ['Signia', 'SIGNIA SI2IX_INSIO_2IX_IIC', 'Superior Plus'],
  ['Widex', 'WIDEX WI Moment BTE R 110_MBR3D1', 'Superior Plus'],
  ['Widex', 'WIDEX WI Moment SRIC R D 110_MRR4D1', 'Superior Plus'],
  ['Phonak', 'PHONAK I30_Phonak Virto I30-10 NW O', 'Superior Plus'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_2IX', 'Superior Plus'],
  ['Signia', 'SIGNIA SI2IX_SILK', 'Superior Plus'],
  ['Signia', 'SIGNIA SI2IX_Styletto_2IX', 'Superior Plus'],
  ['ReSound', 'GNR VIVIA4_VI460S-DRWC', 'Superior Plus'],
  ['ReSound', 'GNR VIVIA4_VI461-DRW', 'Superior Plus'],
  ['ReSound', 'GNR VIVIA4_VI462-DRW', 'Superior Plus'],
  ['Unitron', 'UNITRON 3_Moxi S3-R', 'Superior Plus'],
  ['Beltone', 'BELTONE XG4_XG460S-DRWC', 'Superior Plus'],
  ['Beltone', 'BELTONE XG4_XG461-DRW', 'Superior Plus'],
  ['Beltone', 'BELTONE XG4_XG462-DRW', 'Superior Plus'],
  ['ReSound', 'GNR EI4_EI498-DWHC', 'Superior Plus'],
  ['Signia', 'SIGNIA SI2IX_INSIO_2IX_ITC', 'Superior Plus'],
  ['Signia', 'SIGNIA SI2IX_INSIO_2IX_ITE', 'Superior Plus'],
  ['Phonak', 'PHONAK I30_Phonak Virto I30-R', 'Superior Plus'],
  ['Oticon', 'OTICON OTJET_PX1_MBTE_R', 'Superior Plus'],
  ['Oticon', 'OTICON OTJET_PX1_MBTE_T', 'Superior Plus'],
  ['Oticon', 'OTICON OTJET_PX1_MRITE_R', 'Superior Plus'],
  ['Oticon', 'OTICON OTJET_PX1_MRITE_T', 'Superior Plus'],
  ['Beltone', 'BELTONE XG4_XG498-DWHC', 'Superior Plus'],
  ['Unitron', 'UNITRON 3_Insera S3-10 NW O', 'Superior Plus'],
  ['Unitron', 'UNITRON 3_Insera S3-R', 'Superior Plus'],
  ['Widex', 'WIDEX WI Smart RIC 110_MRRLD1', 'Superior Plus'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_M_2IX', 'Superior Plus'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_P_2IX', 'Superior Plus'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_SP_2IX', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXH3_XH3CIC', 'Superior Plus'],
  ['Beltone', 'BELTONE BTXH3_XH3ITCB', 'Superior Plus'],
  ['Starkey', 'STARKEY 1200_STARKEY.EVOLV AI.1200.BTE.R.STD', 'Superior Plus'],
  ['Starkey', 'STARKEY 12 NW_STARKEY.GENESIS AI(Dir).12 NW.CIC.10.NA', 'Superior Plus'],
  ['Starkey', 'STARKEY 12_STARKEY.GENESIS AI(Dir).12.CIC.312.NA', 'Superior Plus'],
  ['Starkey', 'STARKEY 12_STARKEY.GENESIS AI(Dir).12.HS.R.NA', 'Superior Plus'],
  ['Starkey', 'STARKEY 12_STARKEY.GENESIS AI(Dir).12.ITC.R.NA', 'Superior Plus'],
  ['Starkey', 'STARKEY 12_STARKEY.GENESIS AI(Dir).12.ITE.R.NA', 'Superior Plus'],
  ['Starkey', 'STARKEY 12_STARKEY.G SERIES AI.12.BTE.13.PWRPLS', 'Superior Plus'],
  ['Starkey', 'STARKEY 12_STARKEY.G SERIES AI.12.BTE.13.STD', 'Superior Plus'],
  ['Starkey', 'STARKEY 12_STARKEY.G SERIES AI.12.RIC.312.STD', 'Superior Plus'],
  ['Starkey', 'STARKEY 12_STARKEY.G SERIES AI.12.RIC.R.STD', 'Superior Plus'],
  ['Beltone', 'BELTONE BTBOOSTULTRA6_BBU686-DWHT', 'Advanced'],
  ['Beltone', 'BELTONE BTBOOSTULTRA6_BBU695-DWT', 'Advanced'],
  ['Bernafon', 'BERNAFON BER_Encanta_200_mRITE_R', 'Advanced'],
  ['ReSound', 'GNR RSENZOQ5_EQ588-DWHT', 'Advanced'],
  ['ReSound', 'GNR RSENZOQ5_EQ598-DWT', 'Advanced'],
  ['Signia', 'SIGNIA SI3IX_INSIO_3IX_CIC', 'Advanced'],
  ['Signia', 'SIGNIA SI3IX_INSIO_3IX_IIC', 'Advanced'],
  ['Signia', 'SIGNIA SI300_INSIOCHARGEANDGO', 'Advanced'],
  ['Widex', 'WIDEX WI Moment 13D BTE 220_MBB3D2', 'Advanced'],
  ['Widex', 'WIDEX WI Moment CIC 220_MCIC2', 'Advanced'],
  ['Widex', 'WIDEX WI Moment CIC 220_MCICM2', 'Advanced'],
  ['Widex', 'WIDEX WI Custom IM 220 C_MIM2C', 'Advanced'],
  ['Widex', 'WIDEX WI Moment IM 220 FS_MIM2F', 'Advanced'],
  ['Widex', 'WIDEX WI Custom IM 220 HS_MIM2H', 'Advanced'],
  ['Widex', 'WIDEX WI Moment IP 220 C_MIP2C', 'Advanced'],
  ['Widex', 'WIDEX WI Custom IP 220 FS_MIP2F', 'Advanced'],
  ['Widex', 'WIDEX WI Moment IP 220 HS_MIP2H', 'Advanced'],
  ['Unitron', 'UNITRON 5_Moxi V5-312', 'Advanced'],
  ['Unitron', 'UNITRON 5_Moxi V5-R', 'Advanced'],
  ['Unitron', 'UNITRON 5_Moxi V5-RT', 'Advanced'],
  ['Widex', 'WIDEX WI Moment RIC 10 220_MRB02', 'Advanced'],
  ['Widex', 'WIDEX WI Moment RIC 312 D 220_MRB2D2', 'Advanced'],
  ['Widex', 'WIDEX WI Moment XP 220 C_MXP2C', 'Advanced'],
  ['Widex', 'WIDEX WI Custom XP 220 FS_MXP2F', 'Advanced'],
  ['Widex', 'WIDEX WI Moment XP 220 HS_MXP2H', 'Advanced'],
  ['ReSound', 'GNR RSNEXIA5_NX560S-DRWC', 'Advanced'],
  ['ReSound', 'GNR RSNEXIA5_NX561-DRW', 'Advanced'],
  ['ReSound', 'GNR RSNEXIA5_NX562-DRW', 'Advanced'],
  ['ReSound', 'GNR RSNEXIA5_NX577-DWC', 'Advanced'],
  ['ReSound', 'GNR RSNEXIA5_NX588-DWC', 'Advanced'],
  ['Phonak', 'PHONAK I50_Phonak Audeo I50-R', 'Advanced'],
  ['Phonak', 'PHONAK L50_Phonak Audeo L50-312', 'Advanced'],
  ['Phonak', 'PHONAK L50_Phonak Audeo L50-R', 'Advanced'],
  ['Phonak', 'PHONAK L50_Phonak Audeo L50-RT', 'Advanced'],
  ['Phonak', 'PHONAK L50_Phonak Naida L50-PR', 'Advanced'],
  ['Phonak', 'PHONAK L50_Phonak Naida L50-SP', 'Advanced'],
  ['Phonak', 'PHONAK L50_Phonak Naida L50-UP', 'Advanced'],
  ['Phonak', 'PHONAK P50_Phonak Virto P50-312', 'Advanced'],
  ['Phonak', 'PHONAK P50_Phonak Virto P50-312 NW O', 'Advanced'],
  ['Signia', 'SIGNIA SI3AX_PURECHARGEANDGO', 'Advanced'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_3IX', 'Advanced'],
  ['Signia', 'SIGNIA SIT3AX_PURECHARGEANDGO', 'Advanced'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_T_3IX', 'Advanced'],
  ['Oticon', 'OTICON OTREAL3_MBTE_R', 'Advanced'],
  ['Oticon', 'OTICON OTREAL3_MBTE_T', 'Advanced'],
  ['Oticon', 'OTICON OTREAL3_MRITE_R', 'Advanced'],
  ['Oticon', 'OTICON OTREAL3_MRITE_T', 'Advanced'],
  ['Signia', 'SIGNIA SI3AX_PURE312', 'Advanced'],
  ['Signia', 'SIGNIA SI_Silk_Charge_And_Go_3IX_L', 'Advanced'],
  ['Signia', 'SIGNIA SI_Silk_Charge_And_Go_3IX_R', 'Advanced'],
  ['Unitron', 'UNITRON 5_Stride V5-PR', 'Advanced'],
  ['Unitron', 'UNITRON 5_Stride V5-UP', 'Advanced'],
  ['Signia', 'SIGNIA SIAX_Styletto 3Ax', 'Advanced'],
  ['Signia', 'SIGNIA SI3IX_Styletto_3IX', 'Advanced'],
  ['Beltone', 'BELTONE BTXC4_XC4CIC', 'Advanced'],
  ['Beltone', 'BELTONE BTXC4_XC4HS', 'Advanced'],
  ['Beltone', 'BELTONE BTXC4_XC4ITC', 'Advanced'],
  ['Beltone', 'BELTONE BTXC4_XC4ITE', 'Advanced'],
  ['Beltone', 'BELTONE BTXD5_XD560-DRWC', 'Advanced'],
  ['Beltone', 'BELTONE BTXD5_XD561-DRW', 'Advanced'],
  ['Beltone', 'BELTONE BTXD5_XD561-DRWC', 'Advanced'],
  ['Beltone', 'BELTONE BTXD5_XD562-DRW', 'Advanced'],
  ['Beltone', 'BELTONE BTXD5_XD577-DWC', 'Advanced'],
  ['Beltone', 'BELTONE BTXD5_XD588-DWC', 'Advanced'],
  ['Beltone', 'BELTONE BTXF5_XF560S-DRWC', 'Advanced'],
  ['Beltone', 'BELTONE BTXF5_XF561-DRW', 'Advanced'],
  ['Beltone', 'BELTONE BTXF5_XF562-DRW', 'Advanced'],
  ['Beltone', 'BELTONE BTXF5_XF577-DWC', 'Advanced'],
  ['Beltone', 'BELTONE BTXF5_XF588-DWC', 'Advanced'],
  ['Oticon', 'OTICON OTZIRCON1_BTE_R', 'Advanced'],
  ['Oticon', 'OTICON OTZIRCON1_BTE_T', 'Advanced'],
  ['Oticon', 'OTICON OTZIRCON1_MRITE_R', 'Advanced'],
  ['Oticon', 'OTICON OTZIRCON1_MRITE_T', 'Advanced'],
  ['Signia', 'SIGNIA SI_INTUIS_M_4_3', 'Advanced'],
  ['Signia', 'SIGNIA SI_INTUIS_P_4_3', 'Advanced'],
  ['Signia', 'SIGNIA SI_INTUIS_SP_4_3', 'Advanced'],
  ['Widex', 'WIDEX WI Moment BTE R 220_MBR3D2', 'Advanced'],
  ['Widex', 'WIDEX WI Moment SRIC R D 220_MRR4D2', 'Advanced'],
  ['Phonak', 'PHONAK I50_Phonak Virto I50-10 NW O', 'Advanced'],
  ['Unitron', 'UNITRON 5_Stride V5-M', 'Advanced'],
  ['Unitron', 'UNITRON 5_Stride V5-SP', 'Advanced'],
  ['ReSound', 'GNR VIVIA5_VI560S-DRWC', 'Advanced'],
  ['ReSound', 'GNR VIVIA5_VI561-DRW', 'Advanced'],
  ['ReSound', 'GNR VIVIA5_VI562-DRW', 'Advanced'],
  ['Unitron', 'UNITRON 5_Moxi S5-R', 'Advanced'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_BCT_3IX', 'Advanced'],
  ['Widex', 'WIDEX WI Allure RIC R D 220', 'Advanced'],
  ['Beltone', 'BELTONE XG5_XG560S-DRWC', 'Advanced'],
  ['Beltone', 'BELTONE XG5_XG561-DRW', 'Advanced'],
  ['Beltone', 'BELTONE XG5_XG562-DRW', 'Advanced'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_M_3IX', 'Advanced'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_P_3IX', 'Advanced'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_SP_3IX', 'Advanced'],
  ['ReSound', 'GNR EI5_EI598-DWHC', 'Advanced'],
  ['Signia', 'SIGNIA SI3IX_INSIO_3IX_ITC', 'Advanced'],
  ['Signia', 'SIGNIA SI3IX_INSIO_3IX_ITE', 'Advanced'],
  ['Phonak', 'PHONAK I50_Phonak Virto I50-R', 'Advanced'],
  ['Beltone', 'BELTONE XG5_XG598-DWHC', 'Advanced'],
  ['Widex', 'WIDEX WI Allure ITE R D 220', 'Advanced'],
  ['Unitron', 'UNITRON 5_Insera S5-10 NW O', 'Advanced'],
  ['Unitron', 'UNITRON 5_Insera S5-R', 'Advanced'],
  ['Widex', 'WIDEX WI Smart RIC 220_MRRLD2', 'Advanced'],
  ['Phonak', 'PHONAK L50_Phonak Naida L50-M', 'Advanced'],
  ['Signia', 'SIGNIA SI_INSIO_Charge_And_Go_CIC_3IX', 'Advanced'],
  ['Widex', 'WIDEX WI Allure BTE R D 220', 'Advanced'],
  ['Starkey', 'STARKEY 1600_STARKEY.EVOLV AI.1600.BTE.R.STD', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.EDGE AI.16.mRIC.R.STD', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.EDGE AI.16.RIC.312.STD', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.EDGE AI.16.RIC.R.STD', 'Advanced'],
  ['Starkey', 'STARKEY 16 NW_STARKEY.SIGNATURE(Dir).16 NW.CIC.10.NA', 'Advanced'],
  ['Starkey', 'STARKEY 16 NW_STARKEY.SIGNATURE.16 NW.CIC.R.NA', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.OMEGA AI(Dir).16.HS.R.NA', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.OMEGA AI(Dir).16.ITC.R.NA', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.OMEGA AI(Dir).16.ITE.R.NA', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.OMEGA AI.16.CIC.312.NA', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.OMEGA AI.16.mRIC.R.STD', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.OMEGA AI.16.RIC.312.STD', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.OMEGA AI.16.RIC.R.STD', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.G SERIES AI.16.BTE.13.PWRPLS', 'Advanced'],
  ['Starkey', 'STARKEY 16_STARKEY.G SERIES AI.16.BTE.13.STD', 'Advanced'],
  ['Beltone', 'BELTONE BTBOOSTULTRA9_BBU986-DWHT', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTBOOSTULTRA9_BBU995-DWT', 'Advanced Plus'],
  ['Bernafon', 'BERNAFON BER_Encanta_300_mRITE_R', 'Advanced Plus'],
  ['ReSound', 'GNR RSENZOQ7_EQ788-DWHT', 'Advanced Plus'],
  ['ReSound', 'GNR RSENZOQ7_EQ798-DWT', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Insera B7-10 NW O', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Insera B7-312', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Insera B7-312 NW O', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI5IX_INSIO_5IX_CIC', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI5IX_INSIO_5IX_IIC', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI500_INSIOCHARGEANDGO', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Moment BTE 13D 330_MBB3D3', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Custom CIC 330_MCIC3', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Custom CIC 330_MCICM3', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Moment IM 330 C_MIM3C', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Custom IM 330 FS_MIM3F', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Moment IM 330 HS_MIM3H', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Custom IP 330 C_MIP3C', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Moment IP 330 FS_MIP3F', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Custom IM 330 HS_MIP3H', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Moxi V7-312', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Moxi V7-R', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Moxi V7-RT', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Moment RIC 330_MRB03', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Moment RIC 312 330_MRB2D3', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Custom XP 330 C_MXP3C', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Moment XP 330 FS_MXP3F', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Custom XP 330 HS_MXP3H', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA5_NX5CIC', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA5_NX5HS', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA5_NX5HSB', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA5_NX5ITC', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA5_NX5ITCB', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA5_NX5ITE', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA5_NX5ITEB', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA7_NX760S-DRWC', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA7_NX761-DRW', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA7_NX762-DRW', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA7_NX777-DWC', 'Advanced Plus'],
  ['ReSound', 'GNR RSNEXIA7_NX788-DWC', 'Advanced Plus'],
  ['Oticon', 'OTICON OTOPN3_OPN3S', 'Advanced Plus'],
  ['Oticon', 'OTICON OTOPN3_OPN3SMRITET', 'Advanced Plus'],
  ['Oticon', 'OTICON OTOPN3_OPN3SPOWERPLUS', 'Advanced Plus'],
  ['Oticon', 'OTICON OTOPN3_OPN3SRMRITE', 'Advanced Plus'],
  ['Oticon', 'OTICON OTOWN3_CIC_10', 'Advanced Plus'],
  ['Oticon', 'OTICON OTOWN3_IIC_10', 'Advanced Plus'],
  ['Oticon', 'OTICON OTOWN3_ITC_312', 'Advanced Plus'],
  ['Oticon', 'OTICON OTOWN3_ITE_312', 'Advanced Plus'],
  ['Phonak', 'PHONAK I70_Phonak Audeo I70-R', 'Advanced Plus'],
  ['Phonak', 'PHONAK L70_Phonak Audeo L70-312', 'Advanced Plus'],
  ['Phonak', 'PHONAK L70_Phonak Audeo L70-R', 'Advanced Plus'],
  ['Phonak', 'PHONAK L70_Phonak Audeo L70-RT', 'Advanced Plus'],
  ['Phonak', 'PHONAK L70_Phonak Naida L70-PR', 'Advanced Plus'],
  ['Phonak', 'PHONAK L70_Phonak Naida L70-SP', 'Advanced Plus'],
  ['Phonak', 'PHONAK L70_Phonak Naida L70-UP', 'Advanced Plus'],
  ['Phonak', 'PHONAK P70_Phonak Virto P70-312', 'Advanced Plus'],
  ['Phonak', 'PHONAK P70_Phonak Virto P70-312 NW O', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI5AX_PURECHARGEANDGO', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_5IX', 'Advanced Plus'],
  ['Signia', 'SIGNIA SIT5AX_PURECHARGEANDGO', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_T_5IX', 'Advanced Plus'],
  ['Oticon', 'OTICON OTREAL2_MBTE_R', 'Advanced Plus'],
  ['Oticon', 'OTICON OTREAL2_MBTE_T', 'Advanced Plus'],
  ['Oticon', 'OTICON OTREAL2_MRITE_R', 'Advanced Plus'],
  ['Oticon', 'OTICON OTREAL2_MRITE_T', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI5AX_PURE312', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_Silk_Charge_And_Go_5IX_L', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_Silk_Charge_And_Go_5IX_R', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Stride V7-PR', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Stride V7-UP', 'Advanced Plus'],
  ['Signia', 'SIGNIA SIAX_Styletto 5Ax', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI5IX_Styletto_5IX', 'Advanced Plus'],
  ['Oticon', 'OTICON OTXCEED3_XCEED3BTE', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD5_XD5CIC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD5_XD5HS', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD5_XD5ITC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD5_XD5ITE', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD7_XD760-DRWC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD7_XD761-DRW', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD7_XD761-DRWC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD7_XD762-DRW', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD7_XD777-DWC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXD7_XD788-DWC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF5_XF5CIC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF5_XF5HS', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF5_XF5ITC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF5_XF5ITE', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF7_XF760S-DRWC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF7_XF761-DRW', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF7_XF762-DRW', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF7_XF777-DWC', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF7_XF788-DWC', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_INTUIS_M_4_5', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_INTUIS_P_4_5', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_INTUIS_SP_4_5', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Moment BTE R 330_MBR3D3', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Moment SRIC R D 330_MRR4D3', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Smart RIC 330_MRRLD3', 'Advanced Plus'],
  ['Phonak', 'PHONAK I70_Phonak Virto I70-10 NW O', 'Advanced Plus'],
  ['Phonak', 'PHONAK I70_Phonak Virto I70-Titanium', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Stride V7-M', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Stride V7-SP', 'Advanced Plus'],
  ['ReSound', 'GNR VIVIA7_VI760S-DRWC', 'Advanced Plus'],
  ['ReSound', 'GNR VIVIA7_VI761-DRW', 'Advanced Plus'],
  ['ReSound', 'GNR VIVIA7_VI762-DRW', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF5_XF5HSB', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF5_XF5ITCB', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTXF5_XF5ITEB', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Moxi S7-R', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_BCT_5IX', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Allure RIC R D 330', 'Advanced Plus'],
  ['Beltone', 'BELTONE XG7_XG760S-DRWC', 'Advanced Plus'],
  ['Beltone', 'BELTONE XG7_XG761-DRW', 'Advanced Plus'],
  ['Beltone', 'BELTONE XG7_XG762-DRW', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_M_5IX', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_P_5IX', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_SP_5IX', 'Advanced Plus'],
  ['ReSound', 'GNR EI7_EI798-DWHC', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI5IX_INSIO_5IX_ITC', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI5IX_INSIO_5IX_ITE', 'Advanced Plus'],
  ['Phonak', 'PHONAK I70_Phonak Virto I70-R', 'Advanced Plus'],
  ['Beltone', 'BELTONE XG7_XG798-DWHC', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Allure ITE R D 330', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Insera S7-10 NW O', 'Advanced Plus'],
  ['Unitron', 'UNITRON 7_Insera S7-R', 'Advanced Plus'],
  ['Phonak', 'PHONAK L70_Phonak Naida L70-M', 'Advanced Plus'],
  ['Signia', 'SIGNIA SI_INSIO_Charge_And_Go_CIC_5IX', 'Advanced Plus'],
  ['Widex', 'WIDEX WI Allure BTE R D 330', 'Advanced Plus'],
  ['Starkey', 'STARKEY 2000_STARKEY.EVOLV AI.2000.BTE.R.STD', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.EDGE AI.20.mRIC.R.STD', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.EDGE AI.20.RIC.312.STD', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.EDGE AI.20.RIC.R.STD', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20 NW_STARKEY.SIGNATURE(Dir).20 NW.CIC.10.NA', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20 NW_STARKEY.SIGNATURE.20 NW.CIC.R.NA', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.OMEGA AI(Dir).20.HS.R.NA', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.OMEGA AI(Dir).20.ITC.R.NA', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.OMEGA AI(Dir).20.ITE.R.NA', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.OMEGA AI.20.CIC.312.NA', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.OMEGA AI.20.mRIC.R.STD', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.OMEGA AI.20.RIC.312.STD', 'Advanced Plus'],
  ['Starkey', 'STARKEY 20_STARKEY.OMEGA AI.20.RIC.R.STD', 'Advanced Plus'],
  ['Beltone', 'BELTONE BTBOOSTULTRA17_BBU1786-DWHT', 'Specialty'],
  ['Beltone', 'BELTONE BTBOOSTULTRA17_BBU1795-DWT', 'Specialty'],
  ['Bernafon', 'BERNAFON BER_Encanta_400_mRITE_R', 'Specialty'],
  ['ReSound', 'GNR RSENZOQ9_EQ988-DWHT', 'Specialty'],
  ['ReSound', 'GNR RSENZOQ9_EQ998-DWT', 'Specialty'],
  ['Unitron', 'UNITRON 9_Insera B9-10 NW O', 'Specialty'],
  ['Unitron', 'UNITRON 9_Insera B9-312', 'Specialty'],
  ['Unitron', 'UNITRON 9_Insera B9-312 NW O', 'Specialty'],
  ['Signia', 'SIGNIA SI7IX_INSIO_7IX_CIC', 'Specialty'],
  ['Signia', 'SIGNIA SI700_INSIOCHARGEANDGO', 'Specialty'],
  ['Widex', 'WIDEX WI Moment BTE 13D 440_MBB3D4', 'Specialty'],
  ['Widex', 'WIDEX WI Moment CIC 440_MCIC4', 'Specialty'],
  ['Widex', 'WIDEX WI Moment CIC 440_MCICM4', 'Specialty'],
  ['Widex', 'WIDEX WI Moment IM 440 C_MIM4C', 'Specialty'],
  ['Widex', 'WIDEX WI Custom IM 440 FS_MIM4F', 'Specialty'],
  ['Widex', 'WIDEX WI Moment IM 440 HS_MIM4H', 'Specialty'],
  ['Widex', 'WIDEX WI Moment IP 440 C_MIP4C', 'Specialty'],
  ['Widex', 'WIDEX WI Custom IP 440 FS_MIP4F', 'Specialty'],
  ['Widex', 'WIDEX WI Moment IP 440 HS_MIP4H', 'Specialty'],
  ['Oticon', 'OTICON OTMORE1_BTE_R', 'Specialty'],
  ['Oticon', 'OTICON OTMORE1_BTE_T', 'Specialty'],
  ['Oticon', 'OTICON OTMORE1_MRITE_R', 'Specialty'],
  ['Oticon', 'OTICON OTMORE1_MRITE_T', 'Specialty'],
  ['Oticon', 'OTICON OTMORE2_BTE_R', 'Specialty'],
  ['Oticon', 'OTICON OTMORE2_BTE_T', 'Specialty'],
  ['Oticon', 'OTICON OTMORE2_MRITE_R', 'Specialty'],
  ['Oticon', 'OTICON OTMORE2_MRITE_T', 'Specialty'],
  ['Unitron', 'UNITRON 9_Moxi V9-312', 'Specialty'],
  ['Unitron', 'UNITRON 9_Moxi V9-R', 'Specialty'],
  ['Unitron', 'UNITRON 9_Moxi V9-RT', 'Specialty'],
  ['Widex', 'WIDEX WI Moment RIC 10 440_MRB04', 'Specialty'],
  ['Widex', 'WIDEX WI Moment RIC 312 D 440_MRB2D4', 'Specialty'],
  ['Widex', 'WIDEX WI Moment XP 440 C_MXP4C', 'Specialty'],
  ['Widex', 'WIDEX WI Custom XP 440 FS_MXP4F', 'Specialty'],
  ['Widex', 'WIDEX WI Moment XP 440 HS_MXP4H', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA7_NX7CIC', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA7_NX7HS', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA7_NX7HSB', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA7_NX7ITC', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA7_NX7ITCB', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA7_NX7ITE', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA7_NX7ITEB', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX960S-DRWC', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX961-DRW', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX962-DRW', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX977-DWC', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX988-DWC', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX9CIC', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX9HS', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX9HSB', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX9ITC', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX9ITCB', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX9ITE', 'Specialty'],
  ['ReSound', 'GNR RSNEXIA9_NX9ITEB', 'Specialty'],
  ['Oticon', 'OTICON OTOPN1_OPN1SPOWERPLUS', 'Specialty'],
  ['Oticon', 'OTICON OTOPN2_OPN2SMRITE', 'Specialty'],
  ['Oticon', 'OTICON OTOPN2_OPN2SPOWERPLUS', 'Specialty'],
  ['Oticon', 'OTICON OTOPN2_OPN2SRMRITE', 'Specialty'],
  ['Oticon', 'OTICON OTOPN2_OPN2SMRITET', 'Specialty'],
  ['Oticon', 'OTICON OTOPN1_OPN1SMRITE', 'Specialty'],
  ['Oticon', 'OTICON OTOPN1_OPN1SMRITET', 'Specialty'],
  ['Oticon', 'OTICON OTOPN1_OPN1SRMRITE', 'Specialty'],
  ['Oticon', 'OTICON OTOWN1_CIC_10', 'Specialty'],
  ['Oticon', 'OTICON OTOWN1_IIC_10', 'Specialty'],
  ['Oticon', 'OTICON OTOWN1_ITC_312', 'Specialty'],
  ['Oticon', 'OTICON OTOWN1_ITE_312', 'Specialty'],
  ['Oticon', 'OTICON OTOWN2_CIC_10', 'Specialty'],
  ['Oticon', 'OTICON OTOWN2_IIC_10', 'Specialty'],
  ['Oticon', 'OTICON OTOWN2_ITC_312', 'Specialty'],
  ['Oticon', 'OTICON OTOWN2_ITE_312', 'Specialty'],
  ['Phonak', 'PHONAK I70_Phonak Audeo I70-Sphere', 'Specialty'],
  ['Phonak', 'PHONAK I90_Phonak Audeo I90-R', 'Specialty'],
  ['Phonak', 'PHONAK L90_Phonak Audeo L90-312', 'Specialty'],
  ['Phonak', 'PHONAK L90_Phonak Audeo L90-R', 'Specialty'],
  ['Phonak', 'PHONAK L90_Phonak Audeo L90-RT', 'Specialty'],
  ['Phonak', 'PHONAK L90_Phonak Naida L90-PR', 'Specialty'],
  ['Phonak', 'PHONAK L90_Phonak Naida L90-SP', 'Specialty'],
  ['Phonak', 'PHONAK L90_Phonak Naida L90-UP', 'Specialty'],
  ['Phonak', 'PHONAK P90_Phonak Virto P90-312', 'Specialty'],
  ['Phonak', 'PHONAK P90_Phonak Virto P90-312 NW O', 'Specialty'],
  ['Signia', 'SIGNIA SI7AX_PURECHARGEANDGO', 'Specialty'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_7IX', 'Specialty'],
  ['Signia', 'SIGNIA SIT7AX_PURECHARGEANDGO', 'Specialty'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_T_7IX', 'Specialty'],
  ['Oticon', 'OTICON OTREAL1_MBTE_R', 'Specialty'],
  ['Oticon', 'OTICON OTREAL1_MBTE_T', 'Specialty'],
  ['Oticon', 'OTICON OTREAL1_MRITE_R', 'Specialty'],
  ['Oticon', 'OTICON OTREAL1_MRITE_T', 'Specialty'],
  ['Signia', 'SIGNIA SI7AX_PURE312', 'Specialty'],
  ['Signia', 'SIGNIA SI_Silk_Charge_And_Go_7IX_L', 'Specialty'],
  ['Signia', 'SIGNIA SI_Silk_Charge_And_Go_7IX_R', 'Specialty'],
  ['Starkey', 'STARKEY 2400_STARKEY.EVOLV AI.2400.BTE.R.STD', 'Specialty'],
  ['Starkey', 'STARKEY 24 NW_STARKEY.SIGNATURE(Dir).24 NW.CIC.10.NA', 'Specialty'],
  ['Starkey', 'STARKEY 24 NW_STARKEY.SIGNATURE.24 NW.CIC.R.NA', 'Specialty'],
  ['Starkey', 'STARKEY 24 NW_STARKEY.SIGNATURE.24 NW.IIC.10.NA', 'Specialty'],
  ['Unitron', 'UNITRON 9_Stride V9-PR', 'Specialty'],
  ['Unitron', 'UNITRON 9_Stride V9-UP', 'Specialty'],
  ['Signia', 'SIGNIA SIAX_Styletto 7Ax', 'Specialty'],
  ['Signia', 'SIGNIA SI7IX_Styletto_7IX', 'Specialty'],
  ['Oticon', 'OTICON OTXCEED1_XCEED1BTE', 'Specialty'],
  ['Oticon', 'OTICON OTXCEED2_XCEED2BTE', 'Specialty'],
  ['Beltone', 'BELTONE BTXD7_XD7CIC', 'Specialty'],
  ['Beltone', 'BELTONE BTXD7_XD7HS', 'Specialty'],
  ['Beltone', 'BELTONE BTXD7_XD7ITC', 'Specialty'],
  ['Beltone', 'BELTONE BTXD7_XD7ITE', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD960-DRWC', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD961-DRW', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD961-DRWC', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD962-DRW', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD977-DWC', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD988-DWC', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD9CIC', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD9HS', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD9ITC', 'Specialty'],
  ['Beltone', 'BELTONE BTXD9_XD9ITE', 'Specialty'],
  ['Beltone', 'BELTONE BTXF7_XF7CIC', 'Specialty'],
  ['Beltone', 'BELTONE BTXF7_XF7HS', 'Specialty'],
  ['Beltone', 'BELTONE BTXF7_XF7ITC', 'Specialty'],
  ['Beltone', 'BELTONE BTXF7_XF7ITE', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF960S-DRWC', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF961-DRW', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF962-DRW', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF977-DWC', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF988-DWC', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF9CIC', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF9HS', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF9ITC', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF9ITE', 'Specialty'],
  ['Signia', 'SIGNIA SI_Active_Pro_IX', 'Specialty'],
  ['Signia', 'SIGNIA SI_INTUIS_M_4_7', 'Specialty'],
  ['Signia', 'SIGNIA SI_INTUIS_P_4_7', 'Specialty'],
  ['Signia', 'SIGNIA SI_INTUIS_SP_4_7', 'Specialty'],
  ['Widex', 'WIDEX WI Moment BTE 13D 440_MBR3D4', 'Specialty'],
  ['Widex', 'WIDEX WI Moment sRIC R D 440_MRR4D4', 'Specialty'],
  ['Widex', 'WIDEX WI Smart RIC 440_MRRLD4', 'Specialty'],
  ['Phonak', 'PHONAK I90_Phonak Virto I90-10 NW O', 'Specialty'],
  ['Phonak', 'PHONAK I90_Phonak Virto I90-Titanium', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.EDGE AI.24.mRIC.R.STD', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.EDGE AI.24.RIC.312.STD', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.EDGE AI.24.RIC.R.STD', 'Specialty'],
  ['Unitron', 'UNITRON 9_Stride V9-M', 'Specialty'],
  ['Unitron', 'UNITRON 9_Stride V9-SP', 'Specialty'],
  ['ReSound', 'GNR VIVIA9_VI960S-DRWC', 'Specialty'],
  ['ReSound', 'GNR VIVIA9_VI961-DRW', 'Specialty'],
  ['ReSound', 'GNR VIVIA9_VI962-DRW', 'Specialty'],
  ['Beltone', 'BELTONE BTXF7_XF7HSB', 'Specialty'],
  ['Beltone', 'BELTONE BTXF7_XF7ITCB', 'Specialty'],
  ['Beltone', 'BELTONE BTXF7_XF7ITEB', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF9HSB', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF9ITCB', 'Specialty'],
  ['Beltone', 'BELTONE BTXF9_XF9ITEB', 'Specialty'],
  ['Unitron', 'UNITRON 9_Moxi S9-R', 'Specialty'],
  ['Signia', 'SIGNIA SI_Pure_Charge_And_Go_BCT_7IX', 'Specialty'],
  ['Widex', 'WIDEX WI Allure RIC R D 440', 'Specialty'],
  ['Beltone', 'BELTONE XG9_XG960S-DRWC', 'Specialty'],
  ['Beltone', 'BELTONE XG9_XG961-DRW', 'Specialty'],
  ['Beltone', 'BELTONE XG9_XG962-DRW', 'Specialty'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_M_7IX', 'Specialty'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_P_7IX', 'Specialty'],
  ['Signia', 'SIGNIA SI_Motion_Charge_And_Go_SP_7IX', 'Specialty'],
  ['ReSound', 'GNR EI9_EI998-DWHC', 'Specialty'],
  ['Signia', 'SIGNIA SI7IX_INSIO_7IX_ITC', 'Specialty'],
  ['Signia', 'SIGNIA SI7IX_INSIO_7IX_ITE', 'Specialty'],
  ['Phonak', 'PHONAK I90_Phonak Virto I90-R', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.OMEGA AI(Dir).24.HS.R.NA', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.OMEGA AI(Dir).24.ITC.R.NA', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.OMEGA AI(Dir).24.ITE.R.NA', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.OMEGA AI.24.CIC.312.NA', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.OMEGA AI.24.mRIC.R.STD', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.OMEGA AI.24.RIC.312.STD', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.OMEGA AI.24.RIC.R.STD', 'Specialty'],
  ['Beltone', 'BELTONE XG9_XG998-DWHC', 'Specialty'],
  ['Widex', 'WIDEX WI Allure ITE R D 440', 'Specialty'],
  ['Unitron', 'UNITRON 9_Insera S9-10 NW O', 'Specialty'],
  ['Unitron', 'UNITRON 9_Insera S9-R', 'Specialty'],
  ['Phonak', 'PHONAK L90_Phonak Naida L90-M', 'Specialty'],
  ['Signia', 'SIGNIA SI_INSIO_Charge_And_Go_CIC_7IX', 'Specialty'],
  ['Widex', 'WIDEX WI Allure BTE R D 440', 'Specialty'],
  ['Starkey', 'STARKEY 20_STARKEY.G SERIES AI.20.BTE.13.PWRPLS', 'Specialty'],
  ['Starkey', 'STARKEY 20_STARKEY.G SERIES AI.20.BTE.13.STD', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.G SERIES AI.24.BTE.13.PWRPLS', 'Specialty'],
  ['Starkey', 'STARKEY 24_STARKEY.G SERIES AI.24.BTE.13.STD', 'Specialty'],
];

