// Auto-generated from Distil_Nurture_Content_Calendar.xlsx
// 115 content items + 60-month timeline

export const CONTENT_LIBRARY = [
  {
    "n": 1,
    "cat": "welcome",
    "type": "push",
    "ch": "push",
    "title": "Welcome to Better Hearing!",
    "body": "Congratulations on your new hearing aids! We're excited to be part of your hearing journey.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Onboarding",
    "month": "0",
    "tone": "Warm"
  },
  {
    "n": 2,
    "cat": "welcome",
    "type": "video",
    "ch": "in_app",
    "title": "Getting Started with Your Devices",
    "body": "Short video guide to get the most out of your first few days with hearing aids.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Onboarding",
    "month": "0",
    "tone": "Helpful"
  },
  {
    "n": 3,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Your First Week: What to Expect",
    "body": "The adjustment period is normal — here's what's happening and why your brain needs time to readjust to sounds.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Onboarding",
    "month": "0",
    "tone": "Reassuring"
  },
  {
    "n": 4,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "How Are Your New Hearing Aids?",
    "body": "Checking in! If you're experiencing any issues, don't hesitate to reach out.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Onboarding",
    "month": "0-1",
    "tone": "Caring"
  },
  {
    "n": 5,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "The Adjustment Period: Tips for Success",
    "body": "One month in — tips to make sure you're getting the most benefit from your devices.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Onboarding",
    "month": "1",
    "tone": "Encouraging"
  },
  {
    "n": 6,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "Are You Wearing Them Enough?",
    "body": "Consistent wear is key to your brain adapting. Aim for all waking hours!",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Early Adoption",
    "month": "1-2",
    "tone": "Motivational"
  },
  {
    "n": 7,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: The Will",
    "body": "Man tells audiologist his new hearing aids are great — he's changed his will three times just from listening to family conversations.",
    "src": "HearingTracker Forum",
    "url": "https://forum.hearingtracker.com/t/hard-of-hearing-jokes-can-we-laugh-at-ourselves/46142",
    "phase": "Early Adoption",
    "month": "2",
    "tone": "Funny"
  },
  {
    "n": 8,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Selective Hearing",
    "body": "My wife says I have selective hearing. I don't remember her saying that.",
    "src": "Riddles Academy",
    "url": "https://riddlesacademy.com/hearing-aid-puns/",
    "phase": "Settled",
    "month": "5",
    "tone": "Funny"
  },
  {
    "n": 9,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Audiologist at the Beach",
    "body": "Why did the audiologist go to the beach? To hear the waves!",
    "src": "Punsify",
    "url": "https://punsify.com/audiology-puns/",
    "phase": "Settled",
    "month": "8",
    "tone": "Funny"
  },
  {
    "n": 10,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Band Practice",
    "body": "Why did the hearing aid join the band? It wanted to amplify the sound.",
    "src": "Hear Me Out CC",
    "url": "https://hearmeoutcc.com/hearing-aids-jokes/",
    "phase": "Settled",
    "month": "11",
    "tone": "Funny"
  },
  {
    "n": 11,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Best Reception",
    "body": "Why did the hearing aid go to school? To get better reception.",
    "src": "Hear Me Out CC",
    "url": "https://hearmeoutcc.com/hearing-aids-jokes/",
    "phase": "Mid-Life",
    "month": "14",
    "tone": "Funny"
  },
  {
    "n": 12,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Turn It Up",
    "body": "I told my hearing aid a joke. It didn't laugh — turns out it only gets the frequency of my humor.",
    "src": "Punny Pulse",
    "url": "https://punnypulse.com/hearing-puns/",
    "phase": "Mid-Life",
    "month": "17",
    "tone": "Funny"
  },
  {
    "n": 13,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: What?",
    "body": "My friend asked if I got new hearing aids. I said \"What?\" three times before admitting yes.",
    "src": "HearingTracker Forum",
    "url": "https://forum.hearingtracker.com/t/clean-jokes-about-hearing/16629",
    "phase": "Mid-Life",
    "month": "20",
    "tone": "Funny"
  },
  {
    "n": 14,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Ear-ning Aid",
    "body": "Why did the hearing aid apply for a job? It wanted to be an ear-ning aid.",
    "src": "Riddles Academy",
    "url": "https://riddlesacademy.com/hearing-aid-puns/",
    "phase": "Mid-Life",
    "month": "23",
    "tone": "Funny"
  },
  {
    "n": 15,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Hearing Committee",
    "body": "What do you call a group of audiologists? A hear-ing committee!",
    "src": "Punsify",
    "url": "https://punsify.com/audiology-puns/",
    "phase": "Mid-Life",
    "month": "26",
    "tone": "Funny"
  },
  {
    "n": 16,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Sound Investment",
    "body": "Getting hearing aids was a sound investment.",
    "src": "Punny Pulse",
    "url": "https://punnypulse.com/hearing-puns/",
    "phase": "Pre-Donation",
    "month": "32",
    "tone": "Funny"
  },
  {
    "n": 17,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Ear Notes",
    "body": "Why did the audiologist bring a pencil? To take ear notes.",
    "src": "Punsify",
    "url": "https://punsify.com/audiology-puns/",
    "phase": "Pre-Donation",
    "month": "38",
    "tone": "Funny"
  },
  {
    "n": 18,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Sound Advice",
    "body": "My audiologist gives the best sound advice.",
    "src": "Riddles Academy",
    "url": "https://riddlesacademy.com/hearing-aid-puns/",
    "phase": "Upgrade Window",
    "month": "44",
    "tone": "Funny"
  },
  {
    "n": 19,
    "cat": "humor",
    "type": "sms",
    "ch": "sms",
    "title": "Hearing Joke: Ear Responsible",
    "body": "I'm not ignoring you. I'm just ear-responsible sometimes.",
    "src": "Punny Pulse",
    "url": "https://punnypulse.com/hearing-puns/",
    "phase": "Upgrade Window",
    "month": "50",
    "tone": "Funny"
  },
  {
    "n": 20,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "First Quarterly Cleaning!",
    "body": "Professional cleanings keep your devices performing their best. Call us to schedule!",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Early Adoption",
    "month": "3",
    "tone": "Action"
  },
  {
    "n": 21,
    "cat": "maintenance",
    "type": "email",
    "ch": "email",
    "title": "See You at Your Next Cleaning!",
    "body": "Thanks for keeping up with your hearing health. See you in a few months!",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Early Adoption",
    "month": "3",
    "tone": "Warm"
  },
  {
    "n": 22,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "6-Month Cleaning Reminder",
    "body": "Your hearing aids work hard every day. Time for a professional tune-up!",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Settled",
    "month": "6",
    "tone": "Action"
  },
  {
    "n": 23,
    "cat": "maintenance",
    "type": "email",
    "ch": "email",
    "title": "Post-Cleaning Check-In",
    "body": "Hope your devices feel fresh! Remember: daily wipe-down keeps performance up between visits.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Settled",
    "month": "6",
    "tone": "Helpful"
  },
  {
    "n": 24,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "9-Month Cleaning Time",
    "body": "Almost a year! Let's make sure everything is performing perfectly.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Settled",
    "month": "9",
    "tone": "Action"
  },
  {
    "n": 25,
    "cat": "maintenance",
    "type": "email",
    "ch": "email",
    "title": "Happy 1-Year Anniversary!",
    "body": "It's been a whole year since you started your hearing journey. Time for an annual hearing retest!",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Settled",
    "month": "12",
    "tone": "Celebratory"
  },
  {
    "n": 26,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "15-Month Cleaning Reminder",
    "body": "Regular cleanings extend the life of your devices. Let's get you scheduled!",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Mid-Life",
    "month": "15",
    "tone": "Action"
  },
  {
    "n": 27,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "18-Month Cleaning Reminder",
    "body": "Halfway through Year 2! Your devices deserve a checkup — and so do your ears.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Mid-Life",
    "month": "18",
    "tone": "Action"
  },
  {
    "n": 28,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "21-Month Cleaning Reminder",
    "body": "Wax buildup and moisture can sneak up. Time for a professional cleaning!",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Mid-Life",
    "month": "21",
    "tone": "Action"
  },
  {
    "n": 29,
    "cat": "maintenance",
    "type": "email",
    "ch": "email",
    "title": "Happy 2-Year Anniversary!",
    "body": "Two years of better hearing! Let's schedule your annual hearing retest.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Mid-Life",
    "month": "24",
    "tone": "Celebratory"
  },
  {
    "n": 30,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "27-Month Cleaning Reminder",
    "body": "Your devices are over 2 years old now — consistent cleanings are more important than ever.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Mid-Life",
    "month": "27",
    "tone": "Action"
  },
  {
    "n": 31,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "30-Month Cleaning Reminder",
    "body": "Almost 2.5 years! Let's keep your hearing aids in top shape.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Mid-Life",
    "month": "30",
    "tone": "Action"
  },
  {
    "n": 32,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "33-Month Cleaning Reminder",
    "body": "Your devices are aging gracefully — but they still need TLC. Schedule your cleaning!",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Pre-Donation",
    "month": "33",
    "tone": "Action"
  },
  {
    "n": 33,
    "cat": "maintenance",
    "type": "email",
    "ch": "email",
    "title": "Happy 3-Year Anniversary!",
    "body": "Three years of better hearing! Annual retest time. Plus, exciting news about what's next.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Pre-Donation",
    "month": "36",
    "tone": "Celebratory"
  },
  {
    "n": 34,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "39-Month Cleaning",
    "body": "Keeping up your cleaning schedule is the best gift you can give your hearing aids.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Pre-Donation",
    "month": "39",
    "tone": "Action"
  },
  {
    "n": 35,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "42-Month Cleaning",
    "body": "Your hearing aids have been working hard for 3.5 years. They deserve some love!",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Upgrade Window",
    "month": "42",
    "tone": "Action"
  },
  {
    "n": 36,
    "cat": "maintenance",
    "type": "push",
    "ch": "push",
    "title": "45-Month Cleaning",
    "body": "Getting close to upgrade territory! In the meantime, let's keep your current aids sharp.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Upgrade Window",
    "month": "45",
    "tone": "Action"
  },
  {
    "n": 37,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "How Your Ear Actually Works",
    "body": "The journey from sound wave to brain signal is incredible. Here's a quick anatomy lesson.",
    "src": "NIH / NIDCD",
    "url": "https://www.nidcd.nih.gov/health/how-do-we-hear",
    "phase": "Onboarding",
    "month": "1",
    "tone": "Educational"
  },
  {
    "n": 38,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Types of Hearing Loss Explained",
    "body": "Sensorineural, conductive, mixed — what do they mean and which type do you have?",
    "src": "ASHA",
    "url": "https://www.asha.org/public/hearing/types-of-hearing-loss/",
    "phase": "Onboarding",
    "month": "2",
    "tone": "Educational"
  },
  {
    "n": 39,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Hearing Aid Myths Debunked",
    "body": "5 common myths about hearing aids that just aren't true anymore.",
    "src": "Hearing Health Foundation",
    "url": "https://hearinghealthfoundation.org/",
    "phase": "Early Adoption",
    "month": "3",
    "tone": "Educational"
  },
  {
    "n": 40,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "The Link Between Hearing and Brain Health",
    "body": "Your hearing aids aren't just for your ears — they're protecting your brain too.",
    "src": "Johns Hopkins / ACHIEVE Study",
    "url": "https://publichealth.jhu.edu/2023/hearing-aids-may-slow-dementia-onset",
    "phase": "Early Adoption",
    "month": "4",
    "tone": "Educational"
  },
  {
    "n": 41,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Understanding Your Audiogram",
    "body": "What all those lines and numbers mean — a patient-friendly guide to reading your hearing test.",
    "src": "Audiology best practice",
    "url": "",
    "phase": "Settled",
    "month": "7",
    "tone": "Educational"
  },
  {
    "n": 42,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Noise-Induced Hearing Loss: Prevention Tips",
    "body": "Concerts, power tools, earbuds — how to protect the hearing you still have.",
    "src": "CDC / NIOSH",
    "url": "https://www.cdc.gov/hearing-loss-prevention/",
    "phase": "Settled",
    "month": "9",
    "tone": "Educational"
  },
  {
    "n": 43,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Tinnitus: What It Is and What Helps",
    "body": "That ringing in your ears has a name — and there are things you can do about it.",
    "src": "American Tinnitus Association",
    "url": "https://www.ata.org/about-tinnitus/",
    "phase": "Settled",
    "month": "10",
    "tone": "Educational"
  },
  {
    "n": 44,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "How Hearing Aids Have Evolved",
    "body": "From ear trumpets to AI-powered devices — a fun look at hearing tech history.",
    "src": "Hearing Review",
    "url": "https://hearingreview.com/",
    "phase": "Mid-Life",
    "month": "13",
    "tone": "Fun/Educational"
  },
  {
    "n": 45,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Communication Strategies for Better Conversations",
    "body": "Tips for you AND your loved ones to make conversations easier and more enjoyable.",
    "src": "ASHA",
    "url": "https://www.asha.org/",
    "phase": "Mid-Life",
    "month": "16",
    "tone": "Practical"
  },
  {
    "n": 46,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Hearing Loss and Fall Risk",
    "body": "Research shows untreated hearing loss triples your risk of falling. Here's why.",
    "src": "Johns Hopkins",
    "url": "https://publichealth.jhu.edu/",
    "phase": "Mid-Life",
    "month": "19",
    "tone": "Educational"
  },
  {
    "n": 47,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "The Emotional Side of Hearing Loss",
    "body": "It's not just about volume — hearing loss affects confidence, relationships, and mood.",
    "src": "Hearing Health Foundation",
    "url": "https://hearinghealthfoundation.org/",
    "phase": "Mid-Life",
    "month": "22",
    "tone": "Empathetic"
  },
  {
    "n": 48,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Hearing Aid Care Deep Dive: Moisture, Wax Guards & Storage",
    "body": "Advanced tips for keeping your hearing aids in top shape at home between cleanings.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Mid-Life",
    "month": "18",
    "tone": "Practical"
  },
  {
    "n": 49,
    "cat": "research",
    "type": "article",
    "ch": "email",
    "title": "ACHIEVE Study: Hearing Aids Slow Cognitive Decline",
    "body": "Landmark Lancet study shows hearing aids can reduce cognitive decline by 48% in at-risk adults.",
    "src": "The Lancet (2023)",
    "url": "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(23)01406-X/abstract",
    "phase": "Settled",
    "month": "8",
    "tone": "Authoritative"
  },
  {
    "n": 50,
    "cat": "research",
    "type": "article",
    "ch": "email",
    "title": "Hearing Loss and Dementia: The Lancet Commission",
    "body": "Hearing loss is the #1 modifiable risk factor for dementia, according to the Lancet Commission.",
    "src": "Lancet Commission on Dementia",
    "url": "https://www.thelancet.com/commissions/dementia",
    "phase": "Mid-Life",
    "month": "14",
    "tone": "Authoritative"
  },
  {
    "n": 51,
    "cat": "research",
    "type": "article",
    "ch": "email",
    "title": "Social Isolation and Hearing Loss",
    "body": "Systematic review shows hearing loss significantly increases risk of loneliness and social withdrawal.",
    "src": "PubMed / Shukla et al. 2020",
    "url": "https://pubmed.ncbi.nlm.nih.gov/32151193/",
    "phase": "Mid-Life",
    "month": "20",
    "tone": "Empathetic"
  },
  {
    "n": 52,
    "cat": "research",
    "type": "article",
    "ch": "email",
    "title": "Hearing Aids and Depression: Meta-Analysis",
    "body": "Research shows hearing aid use is associated with reduced depressive symptoms in older adults.",
    "src": "Frontiers in Aging Neuroscience",
    "url": "https://www.frontiersin.org/journals/aging-neuroscience/",
    "phase": "Mid-Life",
    "month": "25",
    "tone": "Encouraging"
  },
  {
    "n": 53,
    "cat": "research",
    "type": "article",
    "ch": "email",
    "title": "Consistent Hearing Aid Use Matters",
    "body": "Study shows outcomes improve dramatically with daily, all-waking-hours hearing aid use.",
    "src": "Journal of the AMA",
    "url": "",
    "phase": "Settled",
    "month": "11",
    "tone": "Motivational"
  },
  {
    "n": 54,
    "cat": "research",
    "type": "article",
    "ch": "in_app",
    "title": "Hearing Loss Statistics You Should Know",
    "body": "Nearly 1 in 5 Americans have some degree of hearing loss. You're not alone.",
    "src": "NIDCD",
    "url": "https://www.nidcd.nih.gov/health/statistics/quick-statistics-hearing",
    "phase": "Early Adoption",
    "month": "4",
    "tone": "Reassuring"
  },
  {
    "n": 55,
    "cat": "news",
    "type": "article",
    "ch": "in_app",
    "title": "Celebrity Spotlight: Whoopi Goldberg on Hearing Loss",
    "body": "Whoopi openly discusses her hearing loss from years of loud music — and why she wears hearing aids proudly.",
    "src": "Beltone / Soundly",
    "url": "https://www.soundly.com/blog/celebrities-with-hearing-loss",
    "phase": "Settled",
    "month": "6",
    "tone": "Inspirational"
  },
  {
    "n": 56,
    "cat": "news",
    "type": "article",
    "ch": "in_app",
    "title": "Celebrity Spotlight: Huey Lewis",
    "body": "Rock legend Huey Lewis shares his journey with hearing loss and tinnitus from years on stage.",
    "src": "Soundly",
    "url": "https://www.soundly.com/blog/celebrities-with-hearing-loss",
    "phase": "Settled",
    "month": "10",
    "tone": "Inspirational"
  },
  {
    "n": 57,
    "cat": "news",
    "type": "article",
    "ch": "in_app",
    "title": "Celebrity Spotlight: Halle Berry",
    "body": "Oscar-winner Halle Berry lost 80% of hearing in one ear — and hasn't let it slow her down.",
    "src": "InnoCaption",
    "url": "https://www.innocaption.com/recentnews/celebrities-hearing-loss",
    "phase": "Mid-Life",
    "month": "16",
    "tone": "Inspirational"
  },
  {
    "n": 58,
    "cat": "news",
    "type": "article",
    "ch": "in_app",
    "title": "Celebrity Spotlight: Bill Clinton",
    "body": "Former President Bill Clinton was fitted with hearing aids at 51 — while still in office.",
    "src": "WebMD",
    "url": "https://www.webmd.com/healthy-aging/ss/slideshow-celebrities-hearing-loss",
    "phase": "Mid-Life",
    "month": "22",
    "tone": "Inspirational"
  },
  {
    "n": 59,
    "cat": "news",
    "type": "article",
    "ch": "in_app",
    "title": "OTC Hearing Aids: What You Need to Know",
    "body": "The FDA opened the door to over-the-counter hearing aids. Here's how they compare to prescription devices.",
    "src": "Consumer Reports",
    "url": "https://www.consumerreports.org/health/hearing-aids/over-the-counter-hearing-aids-brands-comparison-a3246025494/",
    "phase": "Mid-Life",
    "month": "15",
    "tone": "Informative"
  },
  {
    "n": 60,
    "cat": "news",
    "type": "article",
    "ch": "email",
    "title": "Veterans and Hearing Loss: The #1 Service-Connected Disability",
    "body": "Over 3.2 million veterans receive VA disability compensation for tinnitus alone.",
    "src": "VA Research",
    "url": "https://www.research.va.gov/topics/hearing.cfm",
    "phase": "Pre-Donation",
    "month": "34",
    "tone": "Sobering"
  },
  {
    "n": 61,
    "cat": "tech",
    "type": "article",
    "ch": "in_app",
    "title": "AI-Powered Hearing Aids: What's New",
    "body": "Today's hearing aids use artificial intelligence to adapt to your environment in real time.",
    "src": "U.S. Hearing Solutions / Mayo Clinic",
    "url": "https://www.ushearingsolutions.com/blog/hearing-aid-technology-in-2026/",
    "phase": "Mid-Life",
    "month": "13",
    "tone": "Exciting"
  },
  {
    "n": 62,
    "cat": "tech",
    "type": "article",
    "ch": "in_app",
    "title": "Bluetooth & Auracast: Stream Audio Everywhere",
    "body": "New Auracast technology lets you stream audio from airports, theaters, and stadiums directly to your hearing aids.",
    "src": "Hearing Review / CES 2026",
    "url": "https://hearingreview.com/hearing-products/hearing-aids/otc/hearing-technology-innovations-prominent-at-ces-2026",
    "phase": "Mid-Life",
    "month": "19",
    "tone": "Exciting"
  },
  {
    "n": 63,
    "cat": "tech",
    "type": "article",
    "ch": "in_app",
    "title": "Lenire: New Tinnitus Treatment Device",
    "body": "FDA-approved bimodal neuromodulation device shows 79% of patients see significant tinnitus reduction.",
    "src": "Washington Post / ATA",
    "url": "https://www.ata.org/about-tinnitus/therapy-and-treatment-options/new-emerging-therapies/",
    "phase": "Mid-Life",
    "month": "25",
    "tone": "Hopeful"
  },
  {
    "n": 64,
    "cat": "tech",
    "type": "article",
    "ch": "in_app",
    "title": "New Technology Preview: What's Changed Since Your Fitting",
    "body": "Hearing technology advances fast. See what the latest generation of devices can do.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Pre-Donation",
    "month": "36",
    "tone": "Exciting"
  },
  {
    "n": 65,
    "cat": "tech",
    "type": "article",
    "ch": "in_app",
    "title": "Waterproof, Rechargeable, and Invisible: Modern Hearing Aids",
    "body": "IP68 ratings, all-day rechargeable batteries, and virtually invisible designs are now standard.",
    "src": "HearUSA",
    "url": "https://www.hearusa.com/hearing-aids/technology/",
    "phase": "Upgrade Window",
    "month": "42",
    "tone": "Exciting"
  },
  {
    "n": 66,
    "cat": "lifestyle",
    "type": "article",
    "ch": "in_app",
    "title": "Restaurant Tips for Hearing Aid Users",
    "body": "Choose booths over open tables, sit with your back to the wall, and other tricks for noisy dining.",
    "src": "ASHA / Hearing Health",
    "url": "",
    "phase": "Settled",
    "month": "7",
    "tone": "Practical"
  },
  {
    "n": 67,
    "cat": "lifestyle",
    "type": "article",
    "ch": "in_app",
    "title": "Traveling with Hearing Aids",
    "body": "TSA tips, packing essentials, dealing with airline noise, and international hearing care resources.",
    "src": "Hearing Tracker",
    "url": "https://www.hearingtracker.com/",
    "phase": "Settled",
    "month": "10",
    "tone": "Practical"
  },
  {
    "n": 68,
    "cat": "lifestyle",
    "type": "article",
    "ch": "in_app",
    "title": "Exercising with Hearing Aids",
    "body": "Yes, you can work out with them! Tips for sweat management, retention, and sport-specific advice.",
    "src": "Hearing Health",
    "url": "",
    "phase": "Settled",
    "month": "12",
    "tone": "Motivational"
  },
  {
    "n": 69,
    "cat": "lifestyle",
    "type": "article",
    "ch": "in_app",
    "title": "Hearing Aid Accessories You Didn't Know Existed",
    "body": "TV streamers, remote mics, phone clips, and dehumidifiers that can transform your experience.",
    "src": "Manufacturer guides",
    "url": "",
    "phase": "Mid-Life",
    "month": "15",
    "tone": "Helpful"
  },
  {
    "n": 70,
    "cat": "lifestyle",
    "type": "article",
    "ch": "in_app",
    "title": "Music and Hearing Health",
    "body": "How to enjoy concerts, live music, and headphones safely — and how your hearing aids can help.",
    "src": "HHF / NIOSH",
    "url": "",
    "phase": "Mid-Life",
    "month": "21",
    "tone": "Fun"
  },
  {
    "n": 71,
    "cat": "lifestyle",
    "type": "article",
    "ch": "in_app",
    "title": "Holiday Gatherings: Hearing in Noisy Rooms",
    "body": "Survival guide for Thanksgiving, holiday parties, and family reunions with hearing aids.",
    "src": "Audiologist best practice",
    "url": "",
    "phase": "Seasonal",
    "month": "11 or 23",
    "tone": "Practical"
  },
  {
    "n": 72,
    "cat": "emotional",
    "type": "video",
    "ch": "in_app",
    "title": "First-Time Hearing Reactions Compilation",
    "body": "There's nothing like watching someone hear clearly for the first time. Warning: tissues needed.",
    "src": "YouTube compilations",
    "url": "https://www.youtube.com/results?search_query=hearing+for+the+first+time",
    "phase": "Early Adoption",
    "month": "3",
    "tone": "Emotional"
  },
  {
    "n": 73,
    "cat": "emotional",
    "type": "article",
    "ch": "email",
    "title": "What Your Family Wishes You Knew About Your Hearing",
    "body": "A perspective piece from the loved ones of hearing aid users — why your hearing matters to them.",
    "src": "HHF / patient stories",
    "url": "",
    "phase": "Settled",
    "month": "8",
    "tone": "Emotional"
  },
  {
    "n": 74,
    "cat": "emotional",
    "type": "video",
    "ch": "in_app",
    "title": "Cochlear Implant Activation: Moments That Go Viral",
    "body": "These powerful videos remind us why hearing technology changes lives.",
    "src": "YouTube / news outlets",
    "url": "",
    "phase": "Mid-Life",
    "month": "17",
    "tone": "Emotional"
  },
  {
    "n": 75,
    "cat": "emotional",
    "type": "article",
    "ch": "email",
    "title": "A Veteran's Story: Hearing Again After Service",
    "body": "Personal narrative of a veteran who received donated hearing aids through a program like Lima Charlie.",
    "src": "Lima Charlie / VA Research",
    "url": "https://www.research.va.gov/topics/hearing.cfm",
    "phase": "Pre-Donation",
    "month": "35",
    "tone": "Emotional"
  },
  {
    "n": 76,
    "cat": "emotional",
    "type": "article",
    "ch": "email",
    "title": "The Day I Heard My Grandchild's Voice Clearly",
    "body": "Patient story about the moments that make hearing aids worth every penny.",
    "src": "Patient testimonials",
    "url": "",
    "phase": "Settled",
    "month": "12",
    "tone": "Emotional"
  },
  {
    "n": 77,
    "cat": "emotional",
    "type": "article",
    "ch": "email",
    "title": "How Hearing Loss Nearly Cost Me My Marriage",
    "body": "Honest account of how communication breakdown from untreated hearing loss impacts relationships.",
    "src": "Hearing Health Foundation",
    "url": "https://hearinghealthfoundation.org/",
    "phase": "Mid-Life",
    "month": "24",
    "tone": "Honest"
  },
  {
    "n": 78,
    "cat": "seasonal",
    "type": "email",
    "ch": "in_app",
    "title": "Better Hearing Month: Celebrate Your Hearing Journey",
    "body": "May is Better Hearing Month! Share your hearing story and help reduce stigma.",
    "src": "ASHA / AAA",
    "url": "https://www.audiology.org/advocacy/public-awareness/may-is-better-hearing-month/",
    "phase": "Any",
    "month": "May",
    "tone": "Email"
  },
  {
    "n": 79,
    "cat": "seasonal",
    "type": "email",
    "ch": "in_app",
    "title": "World Hearing Day: March 3",
    "body": "Today the world focuses on hearing health. Learn how you can be an advocate.",
    "src": "WHO",
    "url": "https://www.who.int/campaigns/world-hearing-day/2026",
    "phase": "Any",
    "month": "March",
    "tone": "Email"
  },
  {
    "n": 80,
    "cat": "seasonal",
    "type": "article",
    "ch": "in_app",
    "title": "Summer Hearing Aid Care",
    "body": "Heat, humidity, sunscreen, and water — protecting your devices through summer.",
    "src": "Manufacturer guides",
    "url": "",
    "phase": "Any",
    "month": "June",
    "tone": "In-App"
  },
  {
    "n": 81,
    "cat": "seasonal",
    "type": "article",
    "ch": "in_app",
    "title": "Concert Season Hearing Protection",
    "body": "Enjoy live music safely this summer with these musician-grade earplug recommendations.",
    "src": "NIOSH / HHF",
    "url": "",
    "phase": "Any",
    "month": "May-Aug",
    "tone": "In-App"
  },
  {
    "n": 82,
    "cat": "seasonal",
    "type": "article",
    "ch": "in_app",
    "title": "Holiday Hearing Survival Guide",
    "body": "Crowded rooms, background music, excited kids — tips for hearing through the holiday chaos.",
    "src": "Audiologist tips",
    "url": "",
    "phase": "Any",
    "month": "Nov-Dec",
    "tone": "In-App"
  },
  {
    "n": 83,
    "cat": "seasonal",
    "type": "push",
    "ch": "in_app",
    "title": "New Year's Hearing Resolution",
    "body": "This year, commit to wearing your hearing aids every waking hour. Your brain will thank you!",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Any",
    "month": "January",
    "tone": "Push"
  },
  {
    "n": 84,
    "cat": "seasonal",
    "type": "article",
    "ch": "in_app",
    "title": "Back to School: Hearing Loss in Kids and Grandkids",
    "body": "Hearing loss affects 2-3 in every 1,000 children. Know the signs for the young people in your life.",
    "src": "NIDCD / CDC",
    "url": "",
    "phase": "Any",
    "month": "Aug-Sep",
    "tone": "In-App"
  },
  {
    "n": 85,
    "cat": "seasonal",
    "type": "article",
    "ch": "in_app",
    "title": "Valentine's Day: Love Languages and Hearing",
    "body": "Communication is the foundation of every relationship. Here's how hearing health strengthens your bonds.",
    "src": "Relationship / hearing health",
    "url": "",
    "phase": "Any",
    "month": "February",
    "tone": "Email"
  },
  {
    "n": 86,
    "cat": "video",
    "type": "video",
    "ch": "in_app",
    "title": "TED Talk: Charles Limb on Hearing and Music",
    "body": "Surgeon and musician Charles Limb asks a profound question about what hearing loss steals from us.",
    "src": "TED",
    "url": "https://www.ted.com/talks/charles_limb_building_the_musical_muscle",
    "phase": "Settled",
    "month": "8",
    "tone": "Thought-provoking"
  },
  {
    "n": 87,
    "cat": "video",
    "type": "video",
    "ch": "in_app",
    "title": "DrCliffAud: Real Hearing Aid Reviews",
    "body": "Audiologist Dr. Cliff Olson's popular YouTube channel with honest hearing aid comparisons.",
    "src": "YouTube - DrCliffAud",
    "url": "https://www.youtube.com/@DrCliffAuD",
    "phase": "Mid-Life",
    "month": "14",
    "tone": "Educational"
  },
  {
    "n": 88,
    "cat": "video",
    "type": "video",
    "ch": "in_app",
    "title": "How Cochlear Implants Work (Animated)",
    "body": "Beautiful animation explaining the science behind cochlear implants in under 5 minutes.",
    "src": "YouTube / medical animation",
    "url": "",
    "phase": "Settled",
    "month": "11",
    "tone": "Educational"
  },
  {
    "n": 89,
    "cat": "video",
    "type": "video",
    "ch": "in_app",
    "title": "Neel Raithatha: Satisfying Ear Cleaning Videos",
    "body": "The Wax Whisperer's viral ear cleaning videos — oddly satisfying and educational.",
    "src": "YouTube - Neel Raithatha",
    "url": "https://www.youtube.com/@NRaithatha",
    "phase": "Mid-Life",
    "month": "17",
    "tone": "Fun"
  },
  {
    "n": 90,
    "cat": "video",
    "type": "video",
    "ch": "in_app",
    "title": "What Does Hearing Loss Actually Sound Like?",
    "body": "Simulation videos that let people with normal hearing experience what different types of hearing loss sound like.",
    "src": "YouTube / audiology channels",
    "url": "",
    "phase": "Early Adoption",
    "month": "4",
    "tone": "Eye-opening"
  },
  {
    "n": 91,
    "cat": "lima_charlie",
    "type": "article",
    "ch": "in_app",
    "title": "Lima Charlie: Hear the Mission",
    "body": "Learn about our program that gives your hearing aids a second life — helping veterans hear again.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Pre-Donation",
    "month": "24",
    "tone": "Inspirational"
  },
  {
    "n": 92,
    "cat": "lima_charlie",
    "type": "video",
    "ch": "in_app",
    "title": "Meet a Veteran Who Heard Again",
    "body": "Watch the story of a veteran whose life changed when a patient donated their devices.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Pre-Donation",
    "month": "27",
    "tone": "Emotional"
  },
  {
    "n": 93,
    "cat": "lima_charlie",
    "type": "article",
    "ch": "email",
    "title": "Why Veterans Need Hearing Aids Most",
    "body": "Hearing loss is the #1 service-connected disability. Over 3.2M veterans have tinnitus.",
    "src": "VA Research",
    "url": "https://www.research.va.gov/topics/hearing.cfm",
    "phase": "Pre-Donation",
    "month": "30",
    "tone": "Informative"
  },
  {
    "n": 94,
    "cat": "lima_charlie",
    "type": "article",
    "ch": "in_app",
    "title": "How the Donation Program Works",
    "body": "It's simple: donate your devices before warranty ends, and we recondition them for a veteran in need.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Pre-Donation",
    "month": "33",
    "tone": "Practical"
  },
  {
    "n": 95,
    "cat": "lima_charlie",
    "type": "push",
    "ch": "push",
    "title": "Your Devices Could Change a Veteran's Life",
    "body": "When you're ready to upgrade, your current hearing aids can serve someone who served us all.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Pre-Donation",
    "month": "34",
    "tone": "Compelling"
  },
  {
    "n": 96,
    "cat": "lima_charlie",
    "type": "email",
    "ch": "email",
    "title": "Lima Charlie Donor Spotlight",
    "body": "Read how another patient just like you donated their devices and made a real difference.",
    "src": "Patient testimonials",
    "url": "",
    "phase": "Pre-Donation",
    "month": "36",
    "tone": "Inspirational"
  },
  {
    "n": 97,
    "cat": "lima_charlie",
    "type": "article",
    "ch": "in_app",
    "title": "The Circle of Better Hearing",
    "body": "Your hearing journey doesn't end with you — it can begin for someone else. Here's how the cycle works.",
    "src": "Lima Charlie program",
    "url": "",
    "phase": "Pre-Donation",
    "month": "37",
    "tone": "Aspirational"
  },
  {
    "n": 98,
    "cat": "lima_charlie",
    "type": "push",
    "ch": "push",
    "title": "Thinking About Your Next Pair?",
    "body": "When you upgrade, your current aids can go to a veteran. It's the ultimate pay-it-forward.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Upgrade Window",
    "month": "40",
    "tone": "Gentle"
  },
  {
    "n": 99,
    "cat": "upgrade",
    "type": "article",
    "ch": "in_app",
    "title": "New Technology Preview",
    "body": "Hearing technology has advanced since your fitting. See what's new and what it means for you.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Upgrade Window",
    "month": "36",
    "tone": "Exciting"
  },
  {
    "n": 100,
    "cat": "upgrade",
    "type": "push",
    "ch": "push",
    "title": "Ready to Upgrade? Here's What's New",
    "body": "Your devices have served you well. Let's talk about what the latest technology can offer.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Upgrade Window",
    "month": "39",
    "tone": "Exciting"
  },
  {
    "n": 101,
    "cat": "upgrade",
    "type": "article",
    "ch": "in_app",
    "title": "Side-by-Side: Your Current Aids vs. Latest Generation",
    "body": "See exactly what's improved — noise reduction, battery life, connectivity, comfort.",
    "src": "Manufacturer comparisons",
    "url": "",
    "phase": "Upgrade Window",
    "month": "41",
    "tone": "Informative"
  },
  {
    "n": 102,
    "cat": "upgrade",
    "type": "email",
    "ch": "email",
    "title": "Upgrade Offer + Lima Charlie Donation",
    "body": "Upgrade to the latest hearing technology and give your current devices to a veteran through Lima Charlie.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Upgrade Window",
    "month": "42",
    "tone": "Action"
  },
  {
    "n": 103,
    "cat": "upgrade",
    "type": "article",
    "ch": "in_app",
    "title": "What to Expect from Your Upgrade Appointment",
    "body": "New devices, new features, quick adjustment — here's how the upgrade process works.",
    "src": "Clinical workflow",
    "url": "",
    "phase": "Upgrade Window",
    "month": "44",
    "tone": "Reassuring"
  },
  {
    "n": 104,
    "cat": "upgrade",
    "type": "push",
    "ch": "push",
    "title": "Your Warranty Is Ending Soon",
    "body": "Let's schedule a time to discuss your options — upgrade, Lima Charlie donation, or extended care.",
    "src": "Existing Distil seed",
    "url": "",
    "phase": "Upgrade Window",
    "month": "46",
    "tone": "Urgent"
  },
  {
    "n": 105,
    "cat": "upgrade",
    "type": "email",
    "ch": "email",
    "title": "Final Reminder: Warranty Expiring",
    "body": "Your warranty coverage ends soon. Let's make sure you're set up for continued great hearing.",
    "src": "Campaign cadence",
    "url": "",
    "phase": "Upgrade Window",
    "month": "47",
    "tone": "Urgent"
  },
  {
    "n": 106,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Earwax: Friend or Foe?",
    "body": "Everything you ever (and never) wanted to know about cerumen and what it means for hearing aid users.",
    "src": "ASHA / NIH",
    "url": "",
    "phase": "Settled",
    "month": "9",
    "tone": "Fun/Educational"
  },
  {
    "n": 107,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "How Loud Is Too Loud?",
    "body": "Decibel levels of common sounds — from a whisper to a rock concert — and what's safe.",
    "src": "CDC / NIOSH",
    "url": "https://www.cdc.gov/hearing-loss-prevention/",
    "phase": "Settled",
    "month": "6",
    "tone": "Educational"
  },
  {
    "n": 108,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Hearing Loss in One Ear vs. Both",
    "body": "Unilateral vs. bilateral hearing loss — what's different and how treatment approaches vary.",
    "src": "ASHA",
    "url": "",
    "phase": "Mid-Life",
    "month": "16",
    "tone": "Educational"
  },
  {
    "n": 109,
    "cat": "lifestyle",
    "type": "article",
    "ch": "in_app",
    "title": "Best Smartphone Apps for Hearing Aid Users",
    "body": "Sound amplifiers, speech-to-text, noise meters, and other apps that complement your hearing aids.",
    "src": "App reviews",
    "url": "",
    "phase": "Settled",
    "month": "5",
    "tone": "Practical"
  },
  {
    "n": 110,
    "cat": "lifestyle",
    "type": "article",
    "ch": "in_app",
    "title": "Hearing-Friendly Home Setup",
    "body": "Simple changes to your home environment that make a big difference — flooring, curtains, TV positioning.",
    "src": "Audiologist tips",
    "url": "",
    "phase": "Settled",
    "month": "7",
    "tone": "Practical"
  },
  {
    "n": 111,
    "cat": "education",
    "type": "article",
    "ch": "in_app",
    "title": "Your Hearing Aids and Telehealth",
    "body": "Many adjustments can now be done remotely. Here's how virtual audiology appointments work.",
    "src": "Telehealth / audiology",
    "url": "",
    "phase": "Mid-Life",
    "month": "13",
    "tone": "Modern"
  },
  {
    "n": 112,
    "cat": "research",
    "type": "article",
    "ch": "email",
    "title": "Hearing Aids and Workplace Productivity",
    "body": "Research shows treating hearing loss significantly improves job performance and earnings.",
    "src": "BHI / workplace studies",
    "url": "https://www.betterhearing.org/",
    "phase": "Mid-Life",
    "month": "18",
    "tone": "Motivational"
  },
  {
    "n": 113,
    "cat": "news",
    "type": "article",
    "ch": "in_app",
    "title": "Apple and Hearing Health",
    "body": "How Apple Watch, AirPods, and iPhone hearing features are changing the accessibility landscape.",
    "src": "Apple / tech news",
    "url": "",
    "phase": "Mid-Life",
    "month": "20",
    "tone": "Modern"
  },
  {
    "n": 114,
    "cat": "education",
    "type": "article",
    "ch": "email",
    "title": "Ototoxic Medications: Drugs That Can Affect Hearing",
    "body": "Certain medications can impact your hearing. Know what to watch for and discuss with your doctor.",
    "src": "ATA / medical reference",
    "url": "",
    "phase": "Mid-Life",
    "month": "26",
    "tone": "Important"
  },
  {
    "n": 115,
    "cat": "lifestyle",
    "type": "article",
    "ch": "in_app",
    "title": "Pet Ownership and Hearing Loss",
    "body": "How pets can actually help hearing aid users — from alerting to sounds to reducing isolation.",
    "src": "Hearing health lifestyle",
    "url": "",
    "phase": "Mid-Life",
    "month": "28",
    "tone": "Heartwarming"
  }
];

export const CAMPAIGN_TIMELINE = [
  {
    "month": 0,
    "phase": "Onboarding",
    "pri": "Welcome to Better Hearing! (Push)",
    "priType": "push",
    "note": "High touch — 3 sends in first week",
    "sec": "Getting Started Video",
    "secType": "video"
  },
  {
    "month": 1,
    "phase": "Onboarding",
    "pri": "Your First Week: What to Expect",
    "priType": "article",
    "note": "Reassurance phase",
    "sec": "How Are Your New Hearing Aids? (Check-in)",
    "secType": "push"
  },
  {
    "month": 2,
    "phase": "Onboarding",
    "pri": "Adjustment Tips for Success",
    "priType": "article",
    "note": "Joke lightens the mood pre-cleaning",
    "sec": "Hearing Joke: The Will",
    "secType": "sms"
  },
  {
    "month": 3,
    "phase": "Early Adoption",
    "pri": "First Quarterly Cleaning Reminder",
    "priType": "push",
    "note": "CLEANING CYCLE: joke → reminder → follow-up",
    "sec": "First-Time Hearing Reactions Video",
    "secType": "video"
  },
  {
    "month": 4,
    "phase": "Early Adoption",
    "pri": "Link Between Hearing and Brain Health",
    "priType": "article",
    "note": "Educational engagement",
    "sec": "What Does Hearing Loss Sound Like? (Video)",
    "secType": "video"
  },
  {
    "month": 5,
    "phase": "Settled",
    "pri": "Hearing Joke: Selective Hearing",
    "priType": "sms",
    "note": "Light touch — joke + practical tip",
    "sec": "Best Smartphone Apps for Hearing Aid Users",
    "secType": "article"
  },
  {
    "month": 6,
    "phase": "Settled",
    "pri": "6-Month Cleaning Reminder",
    "priType": "push",
    "note": "CLEANING CYCLE + celebrity interest",
    "sec": "Whoopi Goldberg on Hearing Loss",
    "secType": "article"
  },
  {
    "month": 7,
    "phase": "Settled",
    "pri": "Restaurant Tips for Hearing Aid Users",
    "priType": "article",
    "note": "Lifestyle engagement — ebb period",
    "sec": "Hearing-Friendly Home Setup",
    "secType": "article"
  },
  {
    "month": 8,
    "phase": "Settled",
    "pri": "ACHIEVE Study: Hearing Aids Slow Cognitive Decline",
    "priType": "email",
    "note": "Science + humor combo",
    "sec": "Hearing Joke: Audiologist at the Beach",
    "secType": "sms"
  },
  {
    "month": 9,
    "phase": "Settled",
    "pri": "9-Month Cleaning Reminder",
    "priType": "push",
    "note": "CLEANING CYCLE",
    "sec": "Noise-Induced Hearing Loss Prevention",
    "secType": "article"
  },
  {
    "month": 10,
    "phase": "Settled",
    "pri": "Tinnitus: What It Is and What Helps",
    "priType": "article",
    "note": "Ebb — educational variety",
    "sec": "Huey Lewis Celebrity Spotlight",
    "secType": "article"
  },
  {
    "month": 11,
    "phase": "Settled",
    "pri": "Hearing Joke: Band Practice",
    "priType": "sms",
    "note": "Light pre-cleaning touch",
    "sec": "How Cochlear Implants Work (Video)",
    "secType": "video"
  },
  {
    "month": 12,
    "phase": "Settled",
    "pri": "Happy 1-Year Anniversary!",
    "priType": "email",
    "note": "MILESTONE — celebratory + practical",
    "sec": "Exercising with Hearing Aids",
    "secType": "article"
  },
  {
    "month": 13,
    "phase": "Mid-Life",
    "pri": "How Hearing Aids Have Evolved",
    "priType": "article",
    "note": "Tech engagement — ebb period",
    "sec": "AI-Powered Hearing Aids",
    "secType": "article"
  },
  {
    "month": 14,
    "phase": "Mid-Life",
    "pri": "Hearing Joke: Best Reception",
    "priType": "sms",
    "note": "Pre-cleaning joke + research",
    "sec": "Lancet Commission on Dementia",
    "secType": "email"
  },
  {
    "month": 15,
    "phase": "Mid-Life",
    "pri": "15-Month Cleaning Reminder",
    "priType": "push",
    "note": "CLEANING CYCLE + industry news",
    "sec": "OTC Hearing Aids: What You Need to Know",
    "secType": "article"
  },
  {
    "month": 16,
    "phase": "Mid-Life",
    "pri": "Communication Strategies",
    "priType": "article",
    "note": "Ebb — educational + inspirational",
    "sec": "Halle Berry Celebrity Spotlight",
    "secType": "article"
  },
  {
    "month": 17,
    "phase": "Mid-Life",
    "pri": "Hearing Joke: Turn It Up",
    "priType": "sms",
    "note": "Emotional engagement",
    "sec": "Cochlear Implant Activation Videos",
    "secType": "video"
  },
  {
    "month": 18,
    "phase": "Mid-Life",
    "pri": "18-Month Cleaning Reminder",
    "priType": "push",
    "note": "CLEANING CYCLE + maintenance education",
    "sec": "Hearing Aid Care Deep Dive",
    "secType": "article"
  },
  {
    "month": 19,
    "phase": "Mid-Life",
    "pri": "Bluetooth & Auracast Technology",
    "priType": "article",
    "note": "Tech + health — ebb period",
    "sec": "Hearing Loss and Fall Risk",
    "secType": "article"
  },
  {
    "month": 20,
    "phase": "Mid-Life",
    "pri": "Hearing Joke: What?",
    "priType": "sms",
    "note": "Pre-cleaning joke + research",
    "sec": "Social Isolation and Hearing Loss Study",
    "secType": "email"
  },
  {
    "month": 21,
    "phase": "Mid-Life",
    "pri": "21-Month Cleaning Reminder",
    "priType": "push",
    "note": "CLEANING CYCLE",
    "sec": "Music and Hearing Health",
    "secType": "article"
  },
  {
    "month": 22,
    "phase": "Mid-Life",
    "pri": "Bill Clinton Celebrity Spotlight",
    "priType": "article",
    "note": "Ebb — human interest",
    "sec": "The Emotional Side of Hearing Loss",
    "secType": "article"
  },
  {
    "month": 23,
    "phase": "Mid-Life",
    "pri": "Hearing Joke: Ear-ning Aid",
    "priType": "sms",
    "note": "Seasonal if Nov-Dec, or sub another",
    "sec": "Holiday Hearing Survival Guide",
    "secType": "article"
  },
  {
    "month": 24,
    "phase": "Mid-Life",
    "pri": "Happy 2-Year Anniversary! + Lima Charlie Intro",
    "priType": "email",
    "note": "MILESTONE — first Lima Charlie mention",
    "sec": "Lima Charlie: Hear the Mission",
    "secType": "article"
  },
  {
    "month": 25,
    "phase": "Mid-Life",
    "pri": "Lenire Tinnitus Treatment",
    "priType": "article",
    "note": "Ebb — tech + research",
    "sec": "Hearing Aids and Depression Meta-Analysis",
    "secType": "email"
  },
  {
    "month": 26,
    "phase": "Mid-Life",
    "pri": "Hearing Joke: Hearing Committee",
    "priType": "sms",
    "note": "Pre-cleaning joke + important health info",
    "sec": "Ototoxic Medications",
    "secType": "email"
  },
  {
    "month": 27,
    "phase": "Mid-Life",
    "pri": "27-Month Cleaning Reminder",
    "priType": "push",
    "note": "CLEANING CYCLE + Lima Charlie warm-up",
    "sec": "Meet a Veteran Who Heard Again (Video)",
    "secType": "video"
  },
  {
    "month": 28,
    "phase": "Mid-Life",
    "pri": "Pet Ownership and Hearing Loss",
    "priType": "article",
    "note": "Light touch ebb"
  },
  {
    "month": 30,
    "phase": "Mid-Life",
    "pri": "30-Month Cleaning Reminder",
    "priType": "push",
    "note": "CLEANING CYCLE + Lima Charlie education",
    "sec": "Why Veterans Need Hearing Aids Most",
    "secType": "email"
  },
  {
    "month": 32,
    "phase": "Pre-Donation",
    "pri": "Hearing Joke: Sound Investment",
    "priType": "sms",
    "note": "Light pre-cleaning touch"
  },
  {
    "month": 33,
    "phase": "Pre-Donation",
    "pri": "33-Month Cleaning + How Donation Works",
    "priType": "push",
    "note": "CLEANING CYCLE + Lima Charlie practical",
    "sec": "How the Donation Program Works",
    "secType": "article"
  },
  {
    "month": 34,
    "phase": "Pre-Donation",
    "pri": "Veterans and Hearing Loss (#1 Disability)",
    "priType": "email",
    "note": "LIMA CHARLIE RAMP — dual send",
    "sec": "Your Devices Could Change a Life",
    "secType": "push"
  },
  {
    "month": 35,
    "phase": "Pre-Donation",
    "pri": "A Veteran's Story: Hearing Again",
    "priType": "email",
    "note": "Emotional storytelling"
  },
  {
    "month": 36,
    "phase": "Pre-Donation",
    "pri": "Happy 3-Year Anniversary! + New Tech Preview",
    "priType": "email",
    "note": "MILESTONE — upgrade + donation convergence",
    "sec": "Lima Charlie Donor Spotlight",
    "secType": "email"
  },
  {
    "month": 37,
    "phase": "Pre-Donation",
    "pri": "The Circle of Better Hearing",
    "priType": "article",
    "note": "Aspirational — ebb"
  },
  {
    "month": 38,
    "phase": "Pre-Donation",
    "pri": "Hearing Joke: Ear Notes",
    "priType": "sms",
    "note": "Light touch pre-cleaning"
  },
  {
    "month": 39,
    "phase": "Pre-Donation",
    "pri": "39-Month Cleaning + Ready to Upgrade?",
    "priType": "push",
    "note": "CLEANING CYCLE + upgrade nudge"
  },
  {
    "month": 40,
    "phase": "Upgrade Window",
    "pri": "Thinking About Your Next Pair?",
    "priType": "push",
    "note": "Gentle upgrade + donation CTA"
  },
  {
    "month": 41,
    "phase": "Upgrade Window",
    "pri": "Side-by-Side: Old vs. New Generation",
    "priType": "article",
    "note": "Comparison content"
  },
  {
    "month": 42,
    "phase": "Upgrade Window",
    "pri": "42-Month Cleaning + Upgrade Offer",
    "priType": "push",
    "note": "CLEANING CYCLE + upgrade/donation combo",
    "sec": "Upgrade + Lima Charlie Email",
    "secType": "email"
  },
  {
    "month": 44,
    "phase": "Upgrade Window",
    "pri": "Hearing Joke: Sound Advice",
    "priType": "sms",
    "note": "Pre-cleaning joke + reassurance",
    "sec": "What to Expect from Upgrade Appointment",
    "secType": "article"
  },
  {
    "month": 45,
    "phase": "Upgrade Window",
    "pri": "45-Month Cleaning Reminder",
    "priType": "push",
    "note": "CLEANING CYCLE"
  },
  {
    "month": 46,
    "phase": "Upgrade Window",
    "pri": "Your Warranty Is Ending Soon",
    "priType": "push",
    "note": "Urgency message"
  },
  {
    "month": 47,
    "phase": "Upgrade Window",
    "pri": "Final Reminder: Warranty Expiring",
    "priType": "email",
    "note": "Last push"
  },
  {
    "month": 50,
    "phase": "Upgrade Window",
    "pri": "Hearing Joke: Ear Responsible",
    "priType": "sms",
    "note": "Keep relationship warm"
  },
  {
    "month": 52,
    "phase": "Upgrade Window",
    "pri": "4-Year Check-In Email",
    "priType": "email",
    "note": "Personal outreach if still in system"
  },
  {
    "month": 60,
    "phase": "Upgrade Window",
    "pri": "5-Year Anniversary / Re-Engagement",
    "priType": "email",
    "note": "Final lifecycle touchpoint"
  }
];
