-- READY TO APPLY: Run this in Supabase SQL editor or via CLI migration
-- Migration: 004_patient_documents
-- Created: 2026-04-29
-- Description: Stores PDF artifacts (quotes, purchase agreements, kiosk intake
--              receipts) generated by Distil and the IntakeKiosk. Files live in
--              the private 'patient-documents' storage bucket; this table is
--              the metadata index. patient_id is nullable so kiosk PDFs can be
--              archived at submit time (when no patient row exists yet) and
--              backfilled when the intake is matched to a patient.

-- ═══════════════════════════════════════════════════════════════════════════════
-- 1 — patient_documents table
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE patient_documents (
  id            uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  patient_id    uuid REFERENCES patients(id) ON DELETE CASCADE,
  clinic_id     uuid NOT NULL REFERENCES clinics(id),
  staff_id      uuid REFERENCES staff(id),
  intake_id     uuid REFERENCES intakes(id) ON DELETE SET NULL,
  kind          text NOT NULL CHECK (kind IN ('quote','purchase_agreement','kiosk_intake')),
  storage_path  text NOT NULL UNIQUE,
  file_name     text NOT NULL,
  byte_size     integer,
  metadata      jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON patient_documents(patient_id) WHERE patient_id IS NOT NULL;
CREATE INDEX ON patient_documents(intake_id)  WHERE intake_id  IS NOT NULL;
CREATE INDEX ON patient_documents(clinic_id);

-- ═══════════════════════════════════════════════════════════════════════════════
-- 2 — RLS for patient_documents
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE patient_documents ENABLE ROW LEVEL SECURITY;

-- Staff can read documents within their own clinic
CREATE POLICY staff_see_own_clinic_patient_documents
  ON patient_documents
  FOR SELECT
  USING (clinic_id = my_clinic_id());

-- Staff can insert documents into their own clinic (provider-archived quotes / PAs)
CREATE POLICY staff_insert_own_clinic_patient_documents
  ON patient_documents
  FOR INSERT
  WITH CHECK (clinic_id = my_clinic_id());

-- Anon kiosk can insert kiosk_intake docs — write-only, mirrors anyone_insert_intakes.
-- The kiosk knows its clinic_id from the URL/launch config; clinic_id integrity is
-- enforced at the application layer, same as for the intakes table itself.
CREATE POLICY anyone_insert_kiosk_intake_documents
  ON patient_documents
  FOR INSERT
  WITH CHECK (kind = 'kiosk_intake' AND patient_id IS NULL);

-- Staff can update (used to backfill patient_id when matching a kiosk intake to a patient)
CREATE POLICY staff_update_own_clinic_patient_documents
  ON patient_documents
  FOR UPDATE
  USING (clinic_id = my_clinic_id())
  WITH CHECK (clinic_id = my_clinic_id());

-- ═══════════════════════════════════════════════════════════════════════════════
-- 3 — Storage bucket: patient-documents (private, PDFs only)
-- ═══════════════════════════════════════════════════════════════════════════════
-- Path layout:
--   clinics/{clinic_id}/patients/{patient_id}/{kind}/{timestamp}_{filename}.pdf  (provider-archived)
--   clinics/{clinic_id}/intakes/{intake_id}/{timestamp}_{filename}.pdf            (kiosk-archived)
-- The first two path segments (clinics/{clinic_id}) drive RLS; the third segment
-- distinguishes provider vs kiosk origin.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'patient-documents',
  'patient-documents',
  false,
  10 * 1024 * 1024,                       -- 10 MB cap per file
  ARRAY['application/pdf']
)
ON CONFLICT (id) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════════════════
-- 4 — Storage RLS for patient-documents bucket
-- ═══════════════════════════════════════════════════════════════════════════════
-- storage.foldername(name) returns the path segments as a text array.
-- For 'clinics/abc/patients/xyz/quote/2026.pdf' → ['clinics','abc','patients','xyz','quote']

-- Staff can read any object under their own clinic prefix
CREATE POLICY staff_read_patient_documents_storage
  ON storage.objects
  FOR SELECT
  USING (
    bucket_id = 'patient-documents'
    AND (storage.foldername(name))[1] = 'clinics'
    AND (storage.foldername(name))[2] = my_clinic_id()::text
  );

-- Staff can insert objects under their own clinic prefix
CREATE POLICY staff_insert_patient_documents_storage
  ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'patient-documents'
    AND (storage.foldername(name))[1] = 'clinics'
    AND (storage.foldername(name))[2] = my_clinic_id()::text
  );

-- Anon kiosk can insert objects under any clinic's intakes/ subtree.
-- Mirrors anyone_insert_intakes: kiosk is trusted to write its own clinic_id.
-- Provider/staff path ('patients/...') is NOT covered by this policy.
CREATE POLICY anyone_insert_kiosk_documents_storage
  ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'patient-documents'
    AND (storage.foldername(name))[1] = 'clinics'
    AND (storage.foldername(name))[3] = 'intakes'
  );
