-- Seed the legacy_device reference with 17 common trade-in / competitor
-- devices (Costco KS7-KS10, Phonak Marvel/Paradise/Lumity, Signia Nx/AX, Oticon
-- Opn/More, ReSound ONE/Nexia, Starkey Livio/Genesis, Widex Moment/Sheer).
-- Specs researched from manufacturer sheets + HearingTracker; each row carries a
-- source_url + confidence. Idempotent upsert so it can be re-run safely.

insert into public.legacy_device (
  id, manufacturer, brand, model, aliases, release_year, platform, original_tier_label, original_tier_rank, form_factors, channels, directional_mic, rechargeable, bluetooth_streaming, telecoil, ip_rating, notable_features, source_url, confidence
) values
  ('costco-ks7', 'Rexton', 'Costco Kirkland Signature', 'KS7.0', array['KS7','Kirkland Signature 7','Rexton-based','Signia 7px-class'], 2016, 'Rexton/Sivantos (Signia primax-class)', 'Advanced', 3, array['ric'], 20, 'adaptive', false, false, true, null, array['48 processing channels / 20 gain handles','streams via intermediary streamer (no direct-to-phone)','312 battery','4 receiver power levels'], 'https://forum.hearingtracker.com/t/costco-kirkland-signature-7-0-product-information/25240', 'medium'),
  ('costco-ks8', 'Rexton', 'Costco Kirkland Signature', 'KS8.0', array['KS8','Kirkland Signature 8','Signia Pure 312 7Nx-clone','Rexton-based'], 2018, 'Rexton/Sivantos (Signia Nx-class)', 'Advanced', 3, array['ric'], 20, 'adaptive', false, true, true, null, array['Made for iPhone (MFi) direct streaming','48 processing channels / 20 gain handles','spec-identical to Signia Pure 312 7Nx','312 or 13 (T) battery'], 'https://forum.hearingtracker.com/t/costco-kirkland-signature-8-0-product-information/34162', 'high'),
  ('costco-ks9', 'Phonak', 'Costco Kirkland Signature', 'KS9.0', array['KS9','Kirkland Signature 9','Marvel-based','Phonak M90-class'], 2019, 'Phonak Marvel-class (Sonova)', 'Advanced', 3, array['ric'], 20, 'beamforming', false, true, true, 'IP68', array['direct iOS + Android + any-phone Bluetooth streaming','AutoSense OS','20 fine-tuning bands','Marvel M90-equivalent silicon','312 battery (non-rechargeable variant)'], 'https://hearingreview.com/uncategorized/sonova-to-supply-costco-kirkland-signature-ks9-hearing-aids', 'high'),
  ('costco-ks10', 'Phonak', 'Costco Kirkland Signature', 'KS10.0', array['KS10','KS10.0T','Kirkland Signature 10','Paradise-based','Phonak P90-class'], 2021, 'Phonak Paradise-class (Sonova)', 'Premium', 5, array['ric'], 20, 'beamforming', true, true, true, 'IP68', array['Paradise P90-equivalent silicon','motion sensors + Tap Control','Echo Manager, Speech Enhancer','Made for Any Phone Bluetooth (2 active connections)','Li-ion rechargeable','KS10.0T adds telecoil'], 'https://www.hearingtracker.com/hearing-aids/kirkland-signature-costco-10', 'high'),
  ('phonak-audeo-marvel-m90', 'Phonak', 'Phonak', 'Audeo Marvel M90', array['M90','Audeo M90-R','Marvel 90'], 2018, 'Phonak Marvel (AutoSense OS 3.0)', 'Premium', 5, array['ric','bte'], 20, 'beamforming', true, true, true, 'IP68', array['direct iOS + Android + classic Bluetooth streaming','AutoSense OS 3.0','hands-free calls','StereoZoom','echo reduction (M90 only)','Li-ion rechargeable (M-R)'], 'https://www.phonakpro.com/content/dam/phonakpro/gc_us/en/marketing/documents/marvel/028-1905-03_Leaflet_BtB_Phonak_Audeo_Marvel.pdf', 'high'),
  ('phonak-audeo-paradise-p90', 'Phonak', 'Phonak', 'Audeo Paradise P90', array['P90','Audeo P90-R','Paradise 90'], 2020, 'Phonak Paradise (AutoSense OS 4.0)', 'Premium', 5, array['ric','bte'], 20, 'beamforming', true, true, true, 'IP68', array['motion sensors + Tap Control','StereoZoom, Speech Enhancer, Dynamic Noise Cancellation','Made for Any Phone (2 active Bluetooth connections)','AutoSense OS 4.0','Li-ion rechargeable'], 'https://www.phonak.com/en-us/hearing-devices/hearing-aids/audeo-paradise', 'high'),
  ('phonak-audeo-lumity-l90', 'Phonak', 'Phonak', 'Audeo Lumity L90', array['L90','Audeo L90-R','Lumity 90'], 2022, 'Phonak Lumity (AutoSense OS 5.0 / SmartSpeech)', 'Premium', 5, array['ric','bte'], 20, 'beamforming', true, true, true, 'IP68', array['SmartSpeech Technology, StereoZoom 2.0, SpeechSensor','up to 30h battery per charge','Bluetooth Classic + iOS/Android direct streaming','9 automatic programs','Li-ion rechargeable'], 'https://www.phonak.com/en-us/hearing-devices/hearing-aids/audeo-lumity', 'high'),
  ('signia-pure-7nx', 'Signia', 'Signia', 'Pure 312 7Nx', array['7Nx','Pure Nx','Signia Nx generation'], 2018, 'Signia Nx (Own Voice Processing)', 'Premium', 5, array['ric','bte'], 48, 'beamforming', true, true, true, 'IP68', array['Own Voice Processing (OVP)','48 channels','narrow/ultra-HD directionality (beamforming)','Made for iPhone direct streaming','Charge&Go Li-ion rechargeable option'], 'https://www.signia-pro.com/en-us/product-portfolio/signia-nx/', 'high'),
  ('signia-pure-7ax', 'Signia', 'Signia', 'Pure Charge&Go 7AX', array['7AX','Pure AX','Augmented Xperience'], 2021, 'Signia Augmented Xperience (AX) - dual processor', 'Premium', 5, array['ric'], 48, 'beamforming', true, true, false, 'IP68', array['Augmented Focus dual-processor (separate speech + environment)','48 channels','iOS + Android direct streaming','Li-ion Charge&Go rechargeable','T AX variant adds telecoil'], 'https://www.hearingtracker.com/hearing-aids/signia-pure-ax', 'high'),
  ('oticon-opn-1', 'Oticon', 'Oticon', 'Opn 1', array['Opn1','Opn 1 miniRITE','OpenSound'], 2016, 'Oticon Velox (OpenSound Navigator)', 'Premium', 5, array['ric','bte'], 64, 'adaptive', true, true, true, 'IP68', array['OpenSound Navigator (open, non-blocking directionality)','64 processing channels','Made for iPhone (2.4 GHz) streaming','internet/IoT connectivity via If This Then That','retrofit rechargeable (ZPower/Li-ion) option','miniRITE-T telecoil variant'], 'https://www.oticon.com/-/media/oticon-us/main/download-center/opn/product-information/179076us_td_opn1-2-3_minirite-minirite-t_85.pdf', 'high'),
  ('oticon-more-1', 'Oticon', 'Oticon', 'More 1', array['More1','More 1 miniRITE R','Oticon More'], 2021, 'Oticon Polaris (Deep Neural Network / MoreSound Intelligence)', 'Premium', 5, array['ric','bte'], 64, 'adaptive', true, true, true, 'IP68', array['on-board Deep Neural Network (MoreSound Intelligence)','64 channels','MFi + hands-free calling (later ASHA Android)','Li-ion rechargeable (miniRITE R)','miniRITE T telecoil/disposable variant'], 'https://www.earpros.com/hearing-aid-brands/oticon-hearing-aids/more', 'high'),
  ('resound-one-9', 'ReSound', 'ReSound', 'ONE 9', array['ONE 9','One 9','GN ReSound ONE 9','M&RIE'], 2020, 'ReSound (M&RIE third microphone)', 'Premium', 5, array['ric','bte'], 17, 'adaptive', true, true, true, 'IP68', array['M&RIE (Microphone & Receiver-in-Ear) third in-canal mic','17 channels / bands','Made for iPhone + ASHA Android direct streaming','up to 30h Li-ion rechargeable','All Access Directionality'], 'https://www.hearingtracker.com/hearing-aids/resound-one', 'high'),
  ('resound-nexia-9', 'ReSound', 'ReSound', 'Nexia 9', array['Nexia 9','GN ReSound Nexia 9','Auracast'], 2024, 'ReSound (Bluetooth LE Audio / Auracast)', 'Premium', 5, array['ric','bte','ite','itc','cic','iic'], 17, 'adaptive', true, true, true, 'IP68', array['Bluetooth LE Audio + Auracast broadcast reception','17 channels / 20 adjustment bands','iOS + Android direct streaming','up to 30h Li-ion (24h w/ streaming)','smallest ReSound rechargeable RIE'], 'https://www.hearingtracker.com/hearing-aids/resound-nexia', 'high'),
  ('starkey-livio-ai-2400', 'Starkey', 'Starkey', 'Livio AI 2400', array['Livio AI','Livio AI 2400','Healthable'], 2018, 'Starkey Livio (Thrive / Healthable AI)', 'Premium', 5, array['ric','bte','ite','itc','cic'], 24, 'adaptive', true, true, true, 'IP68', array['first ''Healthable'' - heart rate, activity, fall detection, Thrive Assistant','Made for iPhone direct streaming (Android via streamer)','language translation + transcription','Li-ion rechargeable option'], 'https://www.hearingtracker.com/hearing-aids/starkey-livio', 'medium'),
  ('starkey-genesis-ai-24', 'Starkey', 'Starkey', 'Genesis AI 24', array['Genesis AI 24','Genesis 24','Neuro Processor'], 2023, 'Starkey Genesis AI (Neuro Processor)', 'Premium', 5, array['ric','bte','ite','itc','cic','iic'], 24, 'adaptive', true, true, true, 'IP68', array['Neuro Processor with on-board deep neural network','Neuro Sound Technology (up to 80M automatic adjustments/hr)','iOS + Android direct streaming, hands-free iOS calls','health/fitness tracking + fall detection','Li-ion rechargeable (new sealed design)'], 'https://www.hearingtracker.com/hearing-aids/starkey-genesis-ai', 'high'),
  ('widex-moment-440', 'Widex', 'Widex', 'Moment 440', array['Moment 440','mRIC 440','PureSound / ZeroDelay'], 2020, 'Widex Moment (ZeroDelay / PureSound)', 'Premium', 5, array['ric','bte','ite','itc','cic'], 15, 'adaptive', true, true, true, 'IP68', array['ZeroDelay Accelerator / PureSound (ultra-low latency)','15 processing channels / 5 programs','Made for iPhone + ASHA Android streaming','Li-ion rechargeable option','SoundSense Learn AI personalization'], 'https://www.hearingtracker.com/hearing-aids/widex-moment', 'high'),
  ('widex-moment-sheer-440', 'Widex', 'Widex', 'Moment Sheer 440', array['Moment Sheer 440','Sheer sRIC R D','sRIC'], 2022, 'Widex Moment Sheer (PureSound / TruAcoustics)', 'Premium', 5, array['ric','bte','ite','itc','cic'], 15, 'adaptive', true, true, false, 'IP68', array['PureSound ZeroDelay + TruAcoustics personalization','redesigned smaller sRIC R D shell','up to 29h Li-ion rechargeable','iOS + Android direct streaming, hands-free calls','15 processing channels'], 'https://www.hearingaid.org.uk/hearing-aids/widex/moment-sheer', 'high')
on conflict (id) do update set
  manufacturer = excluded.manufacturer,
  brand = excluded.brand,
  model = excluded.model,
  aliases = excluded.aliases,
  release_year = excluded.release_year,
  platform = excluded.platform,
  original_tier_label = excluded.original_tier_label,
  original_tier_rank = excluded.original_tier_rank,
  form_factors = excluded.form_factors,
  channels = excluded.channels,
  directional_mic = excluded.directional_mic,
  rechargeable = excluded.rechargeable,
  bluetooth_streaming = excluded.bluetooth_streaming,
  telecoil = excluded.telecoil,
  ip_rating = excluded.ip_rating,
  notable_features = excluded.notable_features,
  source_url = excluded.source_url,
  confidence = excluded.confidence,
  updated_at = now();
